%% join_strings: join strings using a delimiter
function [outlet] = join_strings(inlet, delim)
outlet = join_strings_loop(inlet{1}, inlet, delim, 2);

function [outlet]  = join_strings_loop(outlet, inlet, delim, index)
if index <= length(inlet)
	outlet = join_strings_loop(strcat(outlet, ...
		                              delim, ...
		                              inlet{index}), ...
		                       inlet, ...
		                       delim, ...
		                       index+1);
end