function [text] = generate_statistics(spectrum, signalname)
global fs deltaf1 deltaf2 thetaf1 thetaf2 alphaf1 alphaf2 betaf1 betaf2 gammaf1 gammaf2
signalinterval = length(spectrum) / fs;
deltapot = calculate_power(spectrum, deltaf1, deltaf2, fs);
thetapot = calculate_power(spectrum, thetaf1, thetaf2, fs);
alphapot = calculate_power(spectrum, alphaf1, alphaf2, fs);
betapot = calculate_power(spectrum, betaf1, betaf2, fs);
gammapot = calculate_power(spectrum, gammaf1, gammaf2, fs);
total = 0;
for n = 1:length(spectrum)/2
    total = total + spectrum(n).^2;
end

text = {...
	['Signal: ' signalname];...
	['Interval: ' num2str(signalinterval)];...
    ['Delta: ' num2str(deltapot)];...
    ['Theta: ' num2str(thetapot)];...
    ['Alpha: ' num2str(alphapot)];...
    ['Beta: ' num2str(betapot)];...
    ['Gamma: ' num2str(gammapot)];...
	['Total: ' num2str(total)]};
