
edit_enable=1;

v5tipofiltro=1;
v5nedit=1;
v5tiniok=0;
v5fminok=0;
v5fmaxok=fs/2;
v5numsig=1;
v5refselect=0;
v5promon=0;
v5errorfile=0;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%SPAINEL PRINCIPAL%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h5editfig=figure('units','normalized',...
    'position',[0.0039,0.0485,0.993,0.89],...
    'menubar','none',...
    'numbertitle','off',...
    'name','Edição de registros',...
    'color','white',...
    'deletefcn','clear h5* v5* f5*;edit_enable=0;');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%SEIXOS%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

v5hini=0.79;
h5axes=axes('units','normalized',...
    'position',[0.05,0.18,0.765,v5hini]);
grid on;
xlabel('Tempo[s]','fontname','arial','fontsize',9)
ylabel('Amplitude[s]','fontname','arial','fontsize',9)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%SMENU ARQUIVO%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

v5color{1,1}='Azul'; v5color{1,2}=0; v5color{1,3}='b';
v5color{2,1}='Vermelho'; v5color{2,2}=0; v5color{2,3}='r';
v5color{3,1}='Verde'; v5color{3,2}=0; v5color{3,3}='g';
v5color{4,1}='Amarelo'; v5color{4,2}=0; v5color{4,3}='y';
v5color{5,1}='Preto'; v5color{5,2}=0; v5color{5,3}='k';
v5color{6,1}='Ciam'; v5color{6,2}=0; v5color{6,3}='c';
v5color{7,1}='Magenta'; v5color{7,2}=0; v5color{7,3}='m';

f5errorsignal_fcn=['beep;'...
        'msgbox(''O arquivo nao tem formato compativel'',''Arquivo invalido'',''warn'');'...
        'v5errorfile=1;'];

f5novoreg_fcn=['if v5numsig>7;'...
        'msgbox(''O numero maximo de sinais simultaneos e 7. Para inserir outro oculte um dos sinais atuais.'',''Numero maximo de sinais apresentados'',''warn'');'...
        'return;'...
    'end;'...
    '[v5signalname,v5signalpath]=uigetfile(''*.ascii'',''Escolha o arquivo do registro'');'...
    'switch ischar(v5signalname);'...
        'case 0;'...
            'return;'...
    'end;'...
    'v5filename=strcat(v5signalpath,v5signalname);'...
    'eval(''load(v5filename)'',f5errorsignal_fcn);'...
    'if v5errorfile==1;'...
        'v5errorfile=0;'...
        'return;'...
    'end;'...
    'h5msnimport=msgbox(''...importando sinal...'',''Espere'',''warn'');'...
    'v5signalname=v5signalname(1:length(v5signalname)-6);'...
    'v5presignal=eval(v5signalname);'...
    'v5signal=((v5presignal+fa)*fb)-fc;'...
    'v5t=0:1/fs:(length(v5signal)-1)/fs;'...
    'v5treg=sprintf('' %5.2f'',max(v5t));'...
    'v5altplot=v5hini/v5numsig;'...
    'set(h5axes,''visible'',''off'');'...
    'if v5numsig>1;'...
        'if str2num(v5treg)~=v5tfinalok;'...
            'beep;'...
            'msgbox(''Todos os registros devem ser do mesmo tamanho'',''Registro invalido'',''warn'');'...
            'delete(h5msnimport);'...
            'return;'...
        'end;'...
        'for i=v5numsig:-1:2;'...
            'set(h5axesedit(i-1),''position'',[0.05,0.18+(v5numsig-i+1)*v5altplot,0.765,(v5altplot-0.02)]);'...
            'axes(h5axesedit(i-1));'...
            'axis tight;'...
        'end;'...
        'set([h5addref h5promediar],''enable'',''on'');'...
    'end;'...
    'v5tfinalok=str2num(v5treg);'...
    'figure(h5editfig);'...
    'h5axesedit(v5numsig)=axes(''position'',[0.05,0.18,0.765,(v5altplot-0.02)],''fontsize'',8,''fontname'',''arial'');'...
    'for i=1:7;'...
        'if v5color{i,2}==0;'...
            'v5color{i,2}=1;'...
            'v5colorname=v5color{i,1};'...
            'v5colorcode=v5color{i,3};'...
            'v5colorposition(v5numsig)=i;'...
            'break;'...
        'end;'...
    'end;'...
    'axes(h5axesedit(v5numsig));'...
    'if v5numsig>1;'...
        'linkaxes(h5axesedit,''x'');'...
    'end;'...
    'v5plot(v5numsig)=plot(v5t,v5signal,v5colorcode);'...
    'v5listsignal{v5numsig}=strcat(v5signalname,''('',v5colorname,'')'');'...
    'v5editmx{v5numsig}=v5listsignal{v5numsig};'...
    'v5listsignal{v5numsig+1}=''Todos'';'...
    'set(h5signals,''string'',v5listsignal);'...
    'set(h5exportar,''string'',v5editmx);'...
    'ylabel(''Amplitude [uV]'',''fontsize'',8,''fontname'',''arial'');'...
    'axis tight;'...
    'grid on;'...
    'set(h5fslabel,''string'',strcat(''Fs [Hz]:'',num2str(fs)));'...
    'set(h5temporegistro,''string'',strcat(''Tempo de registro [s]:'',v5treg));'...
    'v5interval=get(h5axesedit(v5numsig),''xlim'');'...
    'set(h5intervaloatual,''string'',strcat(''Intervalo atual [s]:'',strcat(sprintf('' %5.2f'',v5interval(1)),'':'',sprintf(''%5.2f'',v5interval(2)))));'...
    'set([h5reset h5fslabel h5temporegistro h5intaptxt h5substituiropt h5filtraropt h5intervaloatual h5zoombutton],''enable'',''on'');'...
    'set([h5remover h5signals h5expbutton h5exportar],''enable'',''on'');'...
    'set(h5tfinaledit,''string'',v5treg);'...
    'v5numsig=v5numsig+1;'...
    'delete(h5msnimport);'];

h5menuarquivo=uimenu('label','Arquivo');
h5addreg=uimenu(h5menuarquivo,'label','Novo Registro','callback',f5novoreg_fcn);

h5menusalvar=uimenu(h5menuarquivo,'label','Salvar');
f5salvar_fcn=['switch v5promon;'...
    'case 0;'...
        'v5savesignal=get(h5signals,''value'');'...
        'if v5savesignal==v5numsig;'...
            'msgbox(''Deve-se selecionar um unico sinal'',''Erro de definição'',''warn'');'...
            'return;'...
        'end;'...
        '[v5savename v5savepath]=uiputfile(''*.ascii'',strcat(''Salvar registro editado_'',v5listsignal{v5savesignal}));'...
        'switch ischar(v5savename);'...
            'case 0;'...
                'return;'...
        'end;'...
        'v5savefile=strcat(v5savepath,v5savename);'...
        'v5datasaved=((get(v5plot(v5savesignal),''ydata'')+fc)/fb)-fa;'...
    'case 1;'...
        '[v5savename v5savepath]=uiputfile(''*.ascii'',''Salvar Promedio'');'...
        'switch ischar(v5savename);'...
            'case 0;'...
                'return;'...
        'end;'...
        'v5savefile=strcat(v5savepath,v5savename);'...
        'v5datasaved=((get(v5promplot,''ydata'')+fc)/fb)-fa;'...
    'end;'...
    'v5fid=fopen(v5savefile,''w'');'...
    'for i=1:length(v5datasaved);'...
        'fprintf(v5fid,''%f\n'',v5datasaved(i));'...
    'end;'...
    'fclose(v5fid);'];

h5salvar=uimenu(h5menusalvar,'label','Sinal editado/Promedio','enable','off','callback',f5salvar_fcn);

f5sair_fcn=['v5sairqtn=questdlg(''Deseja fechar o modulo?'',''Sair'',''Sim'',''Não'',''Sim'');'...
    'switch strcmp(''Sim'',v5sairqtn);'...
        'case 1;'...
            'close(h5editfig);'...
            'clear h5* v5* f5*;edit_enable=0;'...
            'edition_enable=0;'...
     'end;'];
 
h5sair=uimenu(h5menuarquivo,'label','Sair','separator','on','callback',f5sair_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%SMENU EXPORTAR%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h5frame4=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.05,0.01,0.765,0.07]);

f5exportar_fcn=['switch v5promon;'...
        'case 0;'...
            'v5figsel=get(h5exportar,''value'');'...
            'vfig_figxdata=get(v5plot(v5figsel),''xdata'');'...
            'vfig_figydata=get(v5plot(v5figsel),''ydata'');'...
            'vfig_figcolor=get(v5plot(v5figsel),''color'');'...
            'vfig_title=v5editmx{v5figsel};'...
            'vfig_axeslim=get(h5axesedit(v5figsel),''xlim'');'...
        'case 1;'...
            'vfig_figxdata=get(v5promplot,''xdata'');'...
            'vfig_figydata=get(v5promplot,''ydata'');'...
            'vfig_figcolor=get(v5promplot,''color'');'...
            'vfig_title=''Promedio'';'...
            'vfig_axeslim=get(h5axes,''xlim'');'...
        'end;'...
    'vfig_figname=vfig_title;'...
    'vfig_figxname=''Tempo [s]'';'...
    'vfig_figyname=''Amplitude [uV]'';'...
    'exportfig;'];

h5expbutton=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.4,0.024,0.07,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Exp. Figura',...
    'callback',f5exportar_fcn);

h5exportar=uicontrol('style','popupmenu',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'backgroundcolor','white',...
    'position',[0.48,0.015,0.1,0.045],...
    'enable','off',...
    'string','Nenhum');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%SINFORMACOES%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h5frame1=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.83,0.82,0.15,0.15]);   

h5infolabel=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.835,0.935,0.1,0.023],...
    'fontname','arial',...
    'fontsize',10,...
    'HorizontalAlignment','left',...
    'FontWeight','bold',...
    'string','REGISTRO');   

h5signals=uicontrol('style','listbox',...
    'backgroundcolor','white',...
    'units','normalized',...
    'position',[0.835,0.83,0.14,0.1],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'enable','off',...
    'string','Nenhum');   

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%EDICAO%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
f5activeeditar_fcn='set(h5editarbutton,''enable'',''on'');';

h5frame2=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.83,0.19,0.15,0.62]);   

h5editoptions=uicontrol('style','text',...
    'units','normalized',...
    'position',[0.835,0.77,0.11,0.023],...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontname','arial',...
    'fontsize',10,...
    'HorizontalAlignment','left',...
    'FontWeight','bold',...
    'string','OPÇÕES DE EDIÇÃO ');   

f5intap_fcn=['switch get(h5intaptxt,''value'');'...
        'case 1;'...
            'set([h5tinicial h5tiniedit h5tfinal h5tfinaledit],''enable'',''off'');'...
            'set(h5tiniedit,''string'',''0'');'...
            'set(h5tfinaledit,''string'',v5treg);'...
        'case 2;'...
            'set([h5tinicial h5tiniedit h5tfinal h5tfinaledit],''enable'',''on'');'...
    'end;'];

h5intaptxt=uicontrol('style','popupmenu',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'backgroundcolor','white',...
    'position',[0.835,0.745,0.098,0.02],...
    'enable','off',...
    'string','Todo o sinal|Definir intervalo [s]',...
    'callback',f5intap_fcn);

h5tinicial=uicontrol('style','text',...
    'units','normalized',...
    'position',[0.835,0.7,0.032,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'string','Tinicial');

h5tiniedit=uicontrol('style','edit',...
    'units','normalized',...
    'position',[0.87,0.697,0.04,0.03],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'backgroundcolor','white',...
    'string','0',...
     'callback',f5activeeditar_fcn);

h5tfinal=uicontrol('style','text',...
    'units','normalized',...
    'position',[0.835,0.66,0.025,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'string','Tfinal');

h5tfinaledit=uicontrol('style','edit',...
    'units','normalized',...
    'position',[0.87,0.657,0.04,0.03],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'backgroundcolor','white',...
    'string','0',...
     'callback',f5activeeditar_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%SUBSTITUIR%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

f5substituir_fcn=['switch get(h5filtraropt,''value'');'...
        'case 1;'...
            'set(h5filtraropt,''value'',0);'...
            'set([h5rejeitabanda h5tipodefiltro h5passabaixas h5passaaltas h5passabanda],''enable'',''off'');'...
            'set([h5frequencias h5fminima h5fminedit h5fmaxima h5fmaxedit],''enable'',''off'');'...
            'set([h5passabaixas h5passaaltas h5passabanda h5rejeitabanda],''value'',0);'...
            'set(h5fminedit,''string'',''0'');'...
            'set(h5fmaxedit,''string'',num2str(fs/2));'...
    'end;'...
    'switch get(h5substituiropt,''value'');'...
        'case 1;'...
            'set([h5editarbutton h5substituirpor h5radiomedia h5radiozero],''enable'',''on'');'...
            'set(h5radiozero,''value'',1);'...
         'case 0;'...
            'if get(h5filtraropt,''value'')==0;'...
                'set(h5editarbutton,''enable'',''off'');'...
            'end;'...
            'set([h5substituirpor h5radiomedia h5radiozero],''enable'',''off'');'...
            'set([h5radiomedia h5radiozero],''value'',0);'...
     'end;'...
     'eval(f5activeeditar_fcn);'];

h5substituiropt=uicontrol('style','checkbox',...
    'units','normalized',...
    'position',[0.835,0.62,0.14,0.02],...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'FontWeight','bold',...
    'enable','off',...
    'string','Substituição de intervalos',...
    'callback',f5substituir_fcn);

h5substituirpor=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.835,0.59,0.06,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'enable','off',...
    'string','Subtituir por: ');   

f5radiomedia_fcn=['if get(h5radiomedia,''value'')==1;'...
        'set(h5radiozero,''value'',0);'...
   'end;',...
   'eval(f5activeeditar_fcn);'];

h5radiomedia=uicontrol('style','radio',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'position',[0.9,0.585,0.06,0.03],...
    'string','Média',...
    'callback',f5radiomedia_fcn);

f5radiozero_fcn=['if get(h5radiozero,''value'')==1;'...
        'set(h5radiomedia,''value'',0);'...
   'end;',...
   'eval(f5activeeditar_fcn);'];

h5radiozero=uicontrol('style','radio',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'position',[0.9,0.555,0.06,0.03],...
    'string','Zero',...
    'callback',f5radiozero_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%FILTRAR%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

f5filtrar_fcn=['switch get(h5substituiropt,''value'');'...
        'case 1;'...
            'set(h5substituiropt,''value'',0);'...
            'eval(f5substituir_fcn);'...
            'set(h5filtraropt,''value'',1);'...
    'end;'...
    'switch get(h5filtraropt,''value'');'...
        'case 1;'...
            'set([h5tipodefiltro h5rejeitabanda h5passabaixas h5passaaltas h5passabanda h5frequencias h5fmaxima h5fmaxedit h5editarbutton],''enable'',''on'');'...
            'set(h5passabaixas,''value'',1);'...
         'case 0;'...
            'if get(h5substituiropt,''value'')==0;'...
                'set(h5editarbutton,''enable'',''off'');'...
            'end;'...
            'set([h5tipodefiltro h5rejeitabanda h5passabaixas h5passaaltas h5passabanda h5frequencias h5fminima h5fminedit h5fmaxima h5fmaxedit],''enable'',''off'');'...
            'set([h5rejeitabanda h5passabaixas h5passaaltas h5passabanda],''value'',0);'...
            'set(h5fminedit,''string'',''0'');'...
            'set(h5fmaxedit,''string'',num2str(fs/2));'...
    'end;',...
    'eval(f5activeeditar_fcn);'];
 
h5filtraropt=uicontrol('style','checkbox',...
    'units','normalized',...
    'position',[0.835,0.53,0.07,0.02],...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontname','arial',...
    'fontsize',9,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','Filtragem',...
    'enable','off',...
    'callback',f5filtrar_fcn);

h5tipodefiltro=uicontrol('style','text',...
    'units','normalized',...
    'position',[0.835,0.5,0.06,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'string','Tipo de filtro');

f5lp_fcn=['if get(h5passabaixas,''value'')==1;'...
        'set([h5passabanda h5passaaltas h5rejeitabanda],''value'',0);'...
        'set([h5fmaxima h5fmaxedit],''enable'',''on'');'...
        'set(h5fminima,''enable'',''off'');'...
        'set(h5fminedit,''enable'',''off'',''string'',''0'');'...
    'end;'...
    'v5tipofiltro=1;'];

h5passabaixas=uicontrol('style','radio',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'position',[0.835,0.465,0.08,0.03],...
    'string','Passa-baixas',...
    'callback',f5lp_fcn);

f5hp_fcn=['if get(h5passaaltas,''value'')==1;'...
        'set([h5passabanda h5passabaixas h5rejeitabanda],''value'',0);'...
        'set(h5fmaxedit,''enable'',''off'',''string'',num2str(fs/2));'...
        'set(h5fmaxima,''enable'',''off'');'...
        'set([h5fminima h5fminedit],''enable'',''on'');'...
    'end;'...
    'v5tipofiltro=2;',...
    'eval(f5activeeditar_fcn);'];

h5passaaltas=uicontrol('style','radio',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'position',[0.835,0.435,0.08,0.03],...
    'string','Passa-altas',...
    'callback',f5hp_fcn);

f5bp_fcn=['if get(h5passabanda,''value'')==1;'...
        'set([h5passabaixas h5passaaltas h5rejeitabanda],''value'',0);'...
        'set([h5fminima h5fmaxima h5fminedit h5fmaxedit],''enable'',''on'');'...
    'end;'...
    'v5tipofiltro=3;',...
    'eval(f5activeeditar_fcn);'];

h5passabanda=uicontrol('style','radio',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'position',[0.835,0.405,0.08,0.03],...
    'string','Passa-banda',...
    'callback',f5bp_fcn);

f5rb_fcn=['if get(h5passabaixas,''value'')==1;'...
        'set([h5passabanda h5passaaltas h5passabaixas],''value'',0);'...
        'set([h5fminima h5fmaxima h5fminedit h5fmaxedit],''enable'',''on'');'...
    'end;'...
    'v5tipofiltro=4;'];

h5rejeitabanda=uicontrol('style','radio',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'position',[0.835,0.375,0.08,0.03],...
    'string','Rejeita-banda',...
    'callback',f5rb_fcn);

h5frequencias=uicontrol('style','text',...
    'units','normalized',...
    'position',[0.835,0.34,0.14,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'string','Definição de freqüências [Hz]');

h5fminima=uicontrol('style','text',...
    'units','normalized',...
    'position',[0.835,0.305,0.025,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'string','Fmin');

h5fminedit=uicontrol('style','edit',...
    'units','normalized',...
    'position',[0.865,0.302,0.04,0.03],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'backgroundcolor','white',...
    'string','0',...
    'callback',f5activeeditar_fcn);

h5fmaxima=uicontrol('style','text',...
    'units','normalized',...
    'position',[0.835,0.265,0.025,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'string','Fmax');

h5fmaxedit=uicontrol('style','edit',...
    'units','normalized',...
    'position',[0.865,0.26,0.04,0.03],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'backgroundcolor','white',...
    'string',num2str(fs/2),...
    'callback',f5activeeditar_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%EDITAR%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

f5signaledit_fcn=['h5selectsignal=get(h5signals,''value'');'...
    'if h5selectsignal==v5refselect;'...
        'msgbox(''Se deseja editar este sinal nao pode estar selecionado como referencia'',''A referencia nao pode ser editada'',''warn'');'...
        'return;'...
    'end;'...
    'if h5selectsignal==v5numsig;'...
        'h5selectsignal=1:v5numsig-1;'...
        'if v5refselect>0;'...
            'h5selectsignal(v5refselect)=[];'...
        'end;'...
    'end;'...
    'eval(f5editar_fcn);'];

f5editar_fcn=['h5msnedit=msgbox(''...editando sinais...'',''Espere'',''warn'');'...
    'for i=1:length(h5selectsignal);'...
        'h5editsignal=h5axesedit(h5selectsignal(i));'...
        'switch get(h5intaptxt,''value'');'...
            'case 1;'...
                'v5editpoints=round((get(h5editsignal,''xlim'')).*fs);'...
                'v5editpoints(1)=v5editpoints(1)+1;'...
            'case 2;'...
                'v5teditminvalue=str2num(get(h5tiniedit,''string''));'...
                'v5teditmaxvalue=str2num(get(h5tfinaledit,''string''));'...
                'if v5teditminvalue<0;'...
                    'set(h5tiniedit,''string'',num2str(v5tiniok));'...
                    'msgbox(''O tempo inicial deve ser positivo'',''Erro de definição'',''warn'');'...
                    'return;'...
                'end;'...
                'if v5teditmaxvalue>str2num(v5treg);'...
                    'set(h5tfinaledit,''string'',num2str(v5tfinalok));'...
                    'msgbox(''O tempo final deve ser menor que o tempo de registro'',''Erro de definição'',''warn'');'...
                    'return;'...
                'end;'...
                'if v5teditminvalue>v5teditmaxvalue;'...
                    'set(h5tiniedit,''string'',num2str(v5tiniok));'...
                    'set(h5tfinaledit,''string'',num2str(v5tfinalok));'...
                    'msgbox(''O tempo final deve ser menor que o tempo inicial'',''Erro de definição'',''warn'');'...
                    'return;'...
                'end;'...
                'v5tiniok=v5teditminvalue;'...
                'v5tfinalok=v5teditmaxvalue;'...
                'v5editpoints(1)=round((v5teditminvalue*fs)+1);'...
                'v5editpoints(2)=round(v5teditmaxvalue*fs);'...
         'end;'...
         'v5tamint=v5editpoints(2)-v5editpoints(1);'...
         'v5editdata=get(v5plot(h5selectsignal(i)),''ydata'');'...
         'v5predit{h5selectsignal(i),v5nedit}=v5editdata;'...
          'switch get(h5substituiropt,''value'');'...
                'case 1;'...
                    'if get(h5radiozero,''value'')==1;'...
                        'v5editdata(v5editpoints(1):v5editpoints(2))=0;'...
                    'else;'...
                        'v5editdata(v5editpoints(1):v5editpoints(2))=mean(v5editdata(v5editpoints(1):v5editpoints(2)));'...
                    'end;'...
                    'set(v5plot(h5selectsignal(i)),''ydata'',v5editdata);'...
                'case 0;'...
                    'v5fft=fft(v5editdata(v5editpoints(1):v5editpoints(2)));'...
                    'v5feditmaxvalue=str2num(get(h5fmaxedit,''string''));'...
                    'v5feditminvalue=str2num(get(h5fminedit,''string''));'...
                    'if v5feditminvalue<0;'...
                        'set(h5fminedit,''string'',num2str(v5fminok));'...
                        'msgbox(''A frequencia minima deve ser positiva'',''Erro de definição'',''warn'');'...
                        'delete(h5msnedit);'...
                        'return;'...
                    'end;'...
                    'if v5feditminvalue>fs/2;'...
                        'set(h5fminedit,''string'',num2str(v5fminok));'...
                        'msgbox(''A frequencia minima deve ser menor que fs/2'',''Erro de definição'',''warn'');'...
                        'delete(h5msnedit);'...
                        'return;'...
                    'end;'...
                    'if v5feditmaxvalue>fs/2;'...
                        'set(h5fmaxedit,''string'',num2str(v5fmaxok));'...
                        'msgbox(''A frequencia maxima deve ser menor que fs/2'',''Erro de definição'',''warn'');'...
                        'delete(h5msnedit);'...
                        'return;'...
                    'end;'...
                    'if v5feditmaxvalue<0;'...
                        'set(h5fmaxedit,''string'',num2str(v5fmaxok));'...
                        'msgbox(''A frequencia maxima deve ser positiva'',''Erro de definição'',''warn'');'...
                        'delete(h5msnedit);'...
                        'return;'...
                    'end;'...
                    'if v5feditminvalue>v5feditmaxvalue;'...
                        'set(h5fmaxedit,''string'',num2str(v5fmaxok));'...
                        'set(h5fminedit,''string'',num2str(v5fminok));'...
                        'msgbox(''A frequencia minima deve ser menor que a maxima'',''Erro de definição'',''warn'');'...
                        'delete(h5msnedit);'...
                        'return;'...
                    'end;'...
                    'v5fmaxok=v5feditmaxvalue;'...
                    'v5fminok=v5feditminvalue;'...
                    'v5fmaxpoint=round(v5feditmaxvalue*v5tamint/fs);'...
                    'v5fmaxpoint2=length(v5fft)-v5fmaxpoint;'...
                    'v5fminpoint=round(v5feditminvalue*v5tamint/fs);'...
                    'v5fminpoint2=length(v5fft)-v5fminpoint;'...
                    'switch v5tipofiltro;'...
                        'case 1;'...
                            'v5fft(v5fmaxpoint:v5fmaxpoint2)=0;'...
                        'case 2;'...
                            'v5fft(1:v5fminpoint)=0;'...
                            'v5fft(v5fminpoint2:length(v5fft))=0;'...
                        'case 3;'...
                            'v5fft(1:v5fminpoint)=0;'...
                            'v5fft(v5fminpoint2:length(v5fft))=0;'...
                            'v5fft(v5fmaxpoint:v5fmaxpoint2)=0;'...
                        'case 4;'...
                            'v5fft(v5fminpoint:v5fmaxpoint)=0;'...
                            'v5fft(v5fmaxpoint2:v5fminpoint2)=0;'...
                    'end;'...
                    'v5editdata(v5editpoints(1):v5editpoints(2))=real(ifft(v5fft));'...
                    'set(v5plot(h5selectsignal(i)),''ydata'',v5editdata);'...
                    'axes(h5axesedit(h5selectsignal(i)));'...
                    'axis tight;'...
            'end;'...
        'end;'...
        'set([h5desfazerbutton h5salvar],''enable'',''on'');'...
        'delete(h5msnedit);'...
        'v5nedit=v5nedit+1;'];

h5editarbutton=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.835,0.2,0.065,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Editar sinal',...
    'callback',f5signaledit_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%DESFAZER%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

f5desfazer_fcn=['[v5fpre v5cpre]=size(v5predit);'...
    'for i=1:v5fpre;'...
            'switch isempty(v5predit{i,v5nedit-1});'...
            'case 0;'...
                'set(v5plot(i),''ydata'',v5predit{i,v5nedit-1});'...
                'axes(h5axesedit(i));'...
                'axis tight;'...
             'end;'...
    'end;'...
    'if v5nedit-2==0;'...
        'set([h5desfazerbutton h5salvar],''enable'',''off'');'...
    'end;'...
    'set(h5intaptxt,''value'',1);'...
    'set(h5tiniedit,''string'',''0'',''enable'',''off'');'...
    'set(h5tfinaledit,''string'',v5treg,''enable'',''off'');'...
    'v5predit(:,v5nedit-1)=[];'...
    'v5nedit=v5nedit-1;'...
    'switch xor(get(h5substituiropt,''value''),get(h5filtraropt,''value''));'...
        'case 1;'...
            'set(h5editarbutton,''enable'',''on'');'...
    'end;'];

h5desfazerbutton=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.91,0.2,0.065,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Desfazer',...
    'callback',f5desfazer_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%ZOOM%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h5frame3=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.83,0.01,0.15,0.17]); 

h5visualizar=uicontrol('style','text',...
    'units','normalized',...
    'position',[0.835,0.143,0.11,0.023],...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontname','arial',...
    'fontsize',10,...
    'HorizontalAlignment','left',...
    'FontWeight','bold',...
    'string','VISUALIZAR ');   
h5zoom=zoom;


f5zoompost_fcn=['switch v5promon;'...
        'case 1;'...
            'v5xlimits=get(h5axes,''xlim'');'...
        'case 0;'...
             'v5xlimits=get(h5zoomaxe,''xlim'');'...
    'end;'...
    'lim=v5xlimits;'...
    'if v5xlimits(1)<0;'...
        'v5xlimits(1)=0;'...
    'end;',...
    'if v5xlimits(2)>str2num(v5treg);'...
        'v5xlimits(2)=str2num(v5treg);'...
    'end;'...
    'switch v5promon;'...
        'case 1;'...
            'set(h5axes,''xlim'',v5xlimits);'...
        'case 0;'...
            'set(h5zoomaxe,''xlim'',v5xlimits);'...
    'end;'...
    'set(h5intervaloatual,''string'',strcat(''Intervalo atual [s]:'',strcat(sprintf('' %5.2f'',v5xlimits(1)),'':'',sprintf(''%5.2f'',v5xlimits(2)))));'...
    'set(h5tiniedit,''string'',sprintf('' %5.2f'',v5xlimits(1)));'...
    'set(h5tfinaledit,''string'',sprintf(''%5.2f'',v5xlimits(2)));'];

f5prezoom_fcn=['switch v5promon;'...
    'case 1;'...
        'axes(h5axes);'...
    'otherwise;'...
        'h5zoomaxe=gca;'...
        'axes(h5zoomaxe);'...
    'end;'];


f5zoombutton_fcn=['switch get(h5zoombutton,''value'');'...
        'case 1;'...
            'set(h5zoom,''enable'',''on'',''actionprecallback'',f5prezoom_fcn,''actionpostcallback'',f5zoompost_fcn);'...
            'set(h5intaptxt,''value'',2);'...
            'set([h5tinicial h5tiniedit h5tfinal h5tfinaledit],''enable'',''on'');'...
        'case 0;'...
            'set(h5zoom,''enable'',''off'');'...
     'end;'];

h5zoombutton=uicontrol('style','toggle',...
    'units','normalized',...
    'position',[0.833,0.09,0.07,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Zoom',...
    'callback',f5zoombutton_fcn);

f5reset_fcn=['v5resetqtn=questdlg(''Deseja reiniciar o modulo?'',''Reiniciar'',''Sim'',''Não'',''Sim'');'...
    'switch strcmp(''Sim'',v5resetqtn);'...
        'case 1;'...
        'delete(h5axesedit);'...
        'switch v5promon;'...
            'case 1;'...
                'set(h5versinal,''enable'',''off'');'...
                'delete(v5promplot);'...
        'end;'...
        'set(h5axes,''visible'',''on'');'...
        'axes(h5axes);'...
        'axis([0 1 0 1]);'...
        'clear h5axesedit v5plot v5listsignal v5colorposition v5predit;'...
        'for i=1:7;'...
            'v5color{i,2}=0;'...
        'end;'...
        'set(h5signals,''value'',1,''string'',''Nenhum'');'...
        'set(h5exportar,''value'',1,''string'',''Nenhum'',''enable'',''off'');'...
        'set([h5tiniedit h5fminedit],''string'',''0'',''enable'',''off'');'...
        'set(h5tfinaledit,''string'',''0'',''enable'',''off'');'...
        'set(h5fmaxedit,''string'',num2str(fs/2),''enable'',''off'');'...
        'set(h5zoom,''enable'',''off'');'...
        'set(h5zoombutton,''value'',0,''enable'',''off'');'...
        'set([h5expbutton h5remref h5reflabel h5signals h5promediar h5referenciar h5addref h5remover h5desfazerbutton h5editarbutton],''enable'',''off'');'...
        'set([h5intaptxt h5fminima h5fminedit h5fmaxima h5passabanda h5passaaltas h5passabaixas h5rejeitabanda],''enable'',''off'');'...
        'set([h5tinicial h5tfinal h5radiomedia h5radiozero h5filtraropt h5substituiropt],''enable'',''off'');'...
        'set([h5reset h5tipodefiltro h5salvar h5frequencias],''enable'',''off'');'...
        'set(h5zoom,''enable'',''off'');'...
        'set(h5fslabel,''string'',''Fs [Hz]:'',''enable'',''off'');'...
        'set(h5temporegistro,''string'',''Tempo de registro [s]:'',''enable'',''off'');'...
        'set(h5intervaloatual,''string'',''Intervalo atual [s]:'',''enable'',''off'');'...
        'set(h5reflabel,''string'',''Referencia:'');'...
        'set([h5radiomedia h5radiozero h5filtraropt h5substituiropt h5passabanda h5passaaltas h5passabaixas h5rejeitabanda],''value'',0);'...
        'v5numsig=1;'...
        'v5nedit=1;'...
     'end;'];

h5reset=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.871,0.03,0.07,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Reiniciar',...
    'callback',f5reset_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%REMOVER%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

f5remover_fcn=['v5remsignal=get(h5signals,''value'');'...
    'if v5remsignal==v5refselect;'...
        'set(h5reflabel,''string'',''Referencia:'',''enable'',''off'');'...
        'set([h5remref h5referenciar],''enable'',''off'');'...
    'else;'...
        'if v5remsignal<v5refselect;'...
            'v5refselect=v5refselect-1;'...
        'end;'...
    'end;'...
    'if v5remsignal==v5numsig;'...
        'delete(h5axesedit);'...
        'set(h5axes,''visible'',''on'');'...
        'clear h5axesedit v5plot v5listsignal v5colorposition v5editmx;'...
        'for i=1:7;'...
            'v5color{i,2}=0;'...
        'end;'...
        'set(h5zoom,''enable'',''off'');'...
        'set(h5zoombutton,''value'',0,''enable'',''off'');'...
        'set(h5signals,''value'',1,''string'',''Nenhum'');'...
        'set(h5exportar,''value'',1,''string'',''Nenhum'',''enable'',''off'');'...
        'set([h5signals h5promediar h5referenciar h5addref h5remover h5desfazerbutton h5editarbutton],''enable'',''off'');'...
        'set([h5intaptxt h5fminima h5fminedit h5fmaxima h5fmaxedit h5passabanda h5passaaltas h5passabaixas],''enable'',''off'');'...
        'set([h5tiniedit h5tinicial h5tfinaledit h5tfinal h5radiomedia h5radiozero h5filtraropt h5substituiropt],''enable'',''off'');'...
        'set([h5tipodefiltro h5salvar h5expbutton h5reset h5frequencias],''enable'',''off'');'...
        'set(h5zoom,''enable'',''off'');'...
        'v5numsig=1;'...
        'if v5nedit>1;'...
            'v5predit(v5remsignal,:)=[];'...
        'end;'...
        'v5nedit=0;'...
        'return;'...
    'end;'...
    'if v5numsig>2;'...
        'delete(h5axesedit(v5remsignal));'...
        'if v5nedit>1;'...
            'v5predit(v5remsignal,:)=[];'...
        'end;'...
        'h5axesedit(v5remsignal)=[];'...
        'v5altplot=v5hini/(v5numsig-2);'...
        'for i=v5numsig-1:-1:2;'...
            'set(h5axesedit(i-1),''position'',[0.05,0.18+(v5numsig-i-1)*v5altplot,0.765,(v5altplot-0.02)]);'...
            'axes(h5axesedit(i-1));'...
            'axis tight;'...
        'end;'...
    'end;'...
    'v5listsignal(v5remsignal)=[];'...
    'v5editmx(v5remsignal)=[];'...
    'if length(v5editmx)==1;'...
        'set([h5addref h5promediar],''enable'',''off'');'...
    'end;'...
    'set(h5signals,''value'',1,''string'',v5listsignal);'...
    'switch isempty(v5editmx);'...
        'case 0;'...
            'set(h5exportar,''value'',1,''string'',v5editmx);'...
        'case 1;'...
            'set(h5exportar,''value'',1,''string'',''Nenhum'');'...
    'end;'...
    'v5plot(v5remsignal)=[];'...
    'v5color{v5colorposition(v5remsignal),2}=0;'...
    'v5colorposition(v5remsignal)=[];'...
    'if v5numsig==2;'...
        'delete(h5axesedit);'...
        'set(h5axes,''visible'',''on'');'...
        'set(h5zoom,''enable'',''off'');'...
        'set(h5zoombutton,''value'',0,''enable'',''off'');'...
        'set(h5signals,''value'',1,''string'',''Nenhum'',''enable'',''off'');'...
        'set([h5signals h5promediar h5referenciar h5addref h5remover h5desfazerbutton h5editarbutton],''enable'',''off'');'...
        'set([h5intaptxt h5fminima h5fminedit h5fmaxima h5fmaxedit h5passabanda h5passaaltas h5passabaixas],''enable'',''off'');'...
        'set([h5tiniedit h5tinicial h5tfinaledit h5tfinal h5radiomedia h5radiozero h5filtraropt h5substituiropt],''enable'',''off'');'...
        'set([h5tipodefiltro h5expbutton h5exportar h5reset h5salvar h5frequencias],''enable'',''off'');'...
        'v5predit=[];'...
        'v5nedit=1;'...
    'end;'...
    'v5numsig=v5numsig-1;'];

h5remover=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.907,0.09,0.07,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Remover',...
    'callback',f5remover_fcn);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%OPERACOES%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

f5addref_fcn=['v5refselect=get(h5signals,''value'');'...
    'if v5refselect==v5numsig;'...
        'beep;'...
        'msgbox(''Deve escolher uma unica referencia'',''Erro de referencia'',''warn'');'...
        'return;'...
    'end;'...
    'v5ref=get(v5plot(v5refselect),''ydata'');'...
    'set(h5reflabel,''string'',strcat(''Referencia:'',v5listsignal(v5refselect)),''enable'',''on'');'...
    'set([h5referenciar h5remref],''enable'',''on'');'];

h5addref=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.057,0.024,0.07,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Selec. Ref.',...
    'callback',f5addref_fcn);

f5remref_fcn=['v5refselect=0;'...
    'v5ref=0;'...
    'set(h5reflabel,''string'',''Referencia:'',''enable'',''off'');'...
    'set([h5referenciar h5remref],''enable'',''off'');'];

h5remref=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.13,0.024,0.07,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Rem. Ref.',...
    'callback',f5remref_fcn);

f5referenciar_fcn=['v5signalselect=get(h5signals,''value'');'...
    'if v5nedit>0;'...
        'v5predit{v5refselect,v5nedit}=[];'...
    'end;'...
    'if v5signalselect==v5numsig;'...
        'v5signalselect=1:v5numsig-1;'...
        'v5signalselect(v5refselect)=[];'...
    'end;'...
    'for i=1:length(v5signalselect);'...
        'v5norefdata=get(v5plot(v5signalselect(i)),''ydata'');'...
        'v5refdata=v5norefdata-v5ref;'...
        'set(v5plot(v5signalselect(i)),''ydata'',v5refdata);'...
        'axes(h5axesedit(v5signalselect(i)));'...
        'axis tight;'...
        'v5predit{v5signalselect(i),v5nedit}=v5norefdata;'...
    'end;',...
    'v5nedit=v5nedit+1;'...
    'set([h5desfazerbutton h5expbutton h5desfazerbutton h5salvar],''enable'',''on'');'];

h5referenciar=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.202,0.024,0.07,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Referenciar',...
    'callback',f5referenciar_fcn);

f5promediar_fcn=['v5promedio=0;'...
            'for i=1:length(v5plot);'...
                'v5promedio=v5promedio+get(v5plot(i),''ydata'');'...
            'end;'...
            'v5promedio=v5promedio./length(v5plot);'...
            'set(h5axesedit,''visible'',''off'');'...
            'set(h5axes,''visible'',''on'');'...
            'set([h5versinal h5expbutton h5salvar],''enable'',''on'');'...
            'set([h5remref h5reflabel h5signals h5promediar h5referenciar h5addref h5desfazerbutton h5editarbutton],''enable'',''off'');'...
            'set([h5intaptxt h5fminima h5fminedit h5fmaxima h5fmaxedit h5passabanda h5passaaltas h5passabaixas],''enable'',''off'');'...
            'set([h5tiniedit h5tinicial h5tfinaledit h5tfinal h5radiomedia h5radiozero h5filtraropt h5substituiropt],''enable'',''off'');'...
            'set([h5remover h5exportar h5tipodefiltro h5frequencias h5rejeitabanda],''enable'',''off'');'...
            'axes(h5axes);'...
            'v5promplot=plot(v5t,v5promedio,''k'');'...
            'grid on;'...
            'axis tight;'...
            'v5promon=1;'];
        
h5promediar=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.66,0.024,0.07,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Promediar',...
    'callback',f5promediar_fcn);

f5versinal_fcn=['delete(v5promplot);'...
    'set(h5axes,''visible'',''off'');'...
    'set(h5axesedit,''visible'',''on'');'...
    'switch get(h5intaptxt,''value'');'...
        'case 2;'...
            'set([h5tiniedit h5tinicial h5tfinaledit h5tfinal],''enable'',''on'');'...
    'end;'...
    'if v5nedit>1;'...
        'set(h5desfazerbutton,''enable'',''on'');'...
    'end;'...
    'switch get(h5substituiropt,''value'');'...
        'case 1;'...
            'set([h5radiomedia h5radiozero],''enable'',''on'');'...
    'end;'...
    'switch get(h5filtraropt,''value'');'...
        'case 1;'...
            'set([h5fminima h5fminedit h5exportar h5fmaxima h5fmaxedit],''enable'',''on'');'...
            'set([h5frequencias h5tipodefiltro h5rejeitabanda h5passabanda h5passaaltas h5passabaixas],''enable'',''on'');'...
    'end;'...
    'if v5refselect>0;'...
        'set([h5remref h5referenciar h5reflabel],''enable'',''on'');'...
    'end;'...
    'set([h5substituiropt h5filtraropt h5intaptxt h5salvar h5signals h5promediar h5addref h5remover],''enable'',''on'');'...
    'set(h5versinal,''enable'',''off'');'...
    'v5promon=0;'];

h5versinal=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.735,0.024,0.07,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Ver sinais',...
    'callback',f5versinal_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%INFO%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h5frame5=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.05,0.085,0.765,0.04]);

h5reflabel=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.1,0.095,0.15,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'enable','off',...
    'string','Referencia'); 

h5fslabel=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.7,0.095,0.1,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'enable','off',...
    'string','Fs [Hz]: ');  

h5temporegistro=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.3,0.095,0.14,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'enable','off',...
    'string','Tempo de registro [s]: ');   

h5intervaloatual=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.5,0.095,0.14,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'enable','off',...
    'string','Intervalo atual [s]: ');   



