%%%%Exportar figuras dwt%%%%%

 h77dwtfigure=figure('units','normalized',...
    'menubar','none',...
    'resize','off',...
    'numbertitle','off',...
    'color','white',...
    'deletefcn','set(h2espectsignalsfft,''enable'',''on'');',...
    'position',[0.1,0.2,0.7,0.7],...
    'deletefcn','clear h77* v77* f77*;');

h77axis=axes('units','normalized',...
    'position',[0.08,0.15,0.85,0.8]);

v77plot=plot(v7figxdata,v7figydata);
set(v77plot,'color',v7figcolor);
xlabel(v7figxname);
switch v7savefig
    case 1
        title(strcat(v7signalname,'-',v7figname));
        ylabel('Magnitude');
    case 0
        title(strcat('Reconstrucao de:',v7signalname));
        ylabel('Amplitude [uV]');
end
axis tight
grid on
set(h77dwtfigure,'name',strcat('Sinal:_',v7figname));


h77text=uicontrol('style','text',...
    'backgroundcolor','white',...
    'units','normalized',...
    'position',[0.08,0.042,0.2,0.03],...
    'fontname','arial',...
    'fontsize',10,...
    'HorizontalAlignment','left',...
    'string','Deseja salvar esta figura?');

f77salvar_fcn=['set([h77text h77salvar h77cancelar],''visible'',''off'');'...
    'set(h77axis,''position'',[0.08,0.1,0.85,0.85]);'...
    '[v77figfile v77figpath]=uiputfile(''*.jpg'',strcat(''Salvar figura_'',v7figname));'...
    'switch ischar(v77figfile);'...
        'case 0;'...
            'close(h77dwtfigure);'...
            'clear h77* v77* f77*;'...
            'return;'...
     'end;'...
     'v77figpathfile=strcat(v77figpath,v77figfile);'...
     'print(h77dwtfigure,''-djpeg90'',v77figpathfile);'...
     'close(h77dwtfigure);'...
     'clear h77* v77* f77*;'];

h77salvar=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'string','Salvar',...
    'position',[0.26,0.035,0.08,0.05],...
    'callback',f77salvar_fcn);

h77cancelar=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'string','Cancelar',...
    'position',[0.36,0.035,0.08,0.05],...
    'callback','close(h77dwtfigure);clear h77* v77* f77*;');
