%%%%Exportar figuras %%%%%

switch exist('v7figcoef','var')
    case 0
        vfig_coef=0;
    case 1
        vfig_coef=v7figcoef;
end

 hfig_dwtfigure=figure('units','normalized',...
    'menubar','none',...
    'resize','off',...
    'numbertitle','off',...
    'color','white',...
    'deletefcn','set(h2espectsignalsfft,''enable'',''on'');',...
    'position',[0.1,0.2,0.7,0.7],...
    'deletefcn','clear hfig_* vfig_* ffig_*;');

hfig_axis=axes('units','normalized',...
    'position',[0.08,0.15,0.85,0.8]);

vfig_plot=plot(vfig_figxdata,vfig_figydata);
set(vfig_plot,'color',vfig_figcolor);
xlabel(vfig_figxname);
ylabel(vfig_figyname);
title(vfig_title);
axis tight
grid on
set(hfig_dwtfigure,'name',strcat('Sinal:_',vfig_figname));
switch vfig_coef
    case 1
        vfig_dataploted=vfig_figydata(vfig_axeslim(1):vfig_axeslim(2));
    case 0
        vfig_dataploted=vfig_figydata(round(vfig_axeslim(1)*fs)+1:floor(vfig_axeslim(2)*fs));
end
set(hfig_axis,'ylim',[min(vfig_dataploted) max(vfig_dataploted)]);
set(hfig_axis,'xlim',vfig_axeslim);


hfig_text=uicontrol('style','text',...
    'backgroundcolor','white',...
    'units','normalized',...
    'position',[0.08,0.042,0.2,0.03],...
    'fontname','arial',...
    'fontsize',10,...
    'HorizontalAlignment','left',...
    'string','Deseja salvar esta figura?');

ffig_salvar_fcn=['set([hfig_text hfig_salvar hfig_cancelar],''visible'',''off'');'...
    'set(hfig_axis,''position'',[0.08,0.1,0.85,0.85]);'...
    '[vfig_figfile vfig_figpath]=uiputfile(''*.jpg'',strcat(''Salvar figura_'',vfig_figname));'...
    'switch ischar(vfig_figfile);'...
        'case 0;'...
            'close(hfig_dwtfigure);'...
            'clear hfig_* vfig_* ffig_*;'...
            'return;'...
     'end;'...
     'vfig_figpathfile=strcat(vfig_figpath,vfig_figfile);'...
     'print(hfig_dwtfigure,''-djpeg90'',vfig_figpathfile);'...
     'close(hfig_dwtfigure);'...
     'clear hfig_* vfig_* ffig_*;'];

hfig_salvar=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'string','Salvar',...
    'position',[0.26,0.035,0.08,0.05],...
    'callback',ffig_salvar_fcn);

hfig_cancelar=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'string','Cancelar',...
    'position',[0.36,0.035,0.08,0.05],...
    'callback','close(hfig_dwtfigure);clear hfig_* vfig_* ffig_*;');
