
%CONFIGURACAO DE RITMOS

v11deltaf1ok=deltaf1;
v11deltaf2ok=deltaf2;
v11thetaf1ok=thetaf1;
v11thetaf2ok=thetaf2;
v11alphaf1ok=alphaf1;
v11alphaf2ok=alphaf2;
v11bethaf1ok=bethaf1;
v11bethaf2ok=bethaf2;
v11gammaf1ok=gammaf1;
v11gammaf2ok=gammaf2;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%PAINEL%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h11ritconfig=figure('units','normalized',...
    'menubar','none',...
    'resize','off',...
    'numbertitle','off',...
    'color','white',...
    'position',[0.35,0.3,0.22,0.5],...
    'name','CONFIGURACAO DE RITMOS',...
    'deletefcn','clear h11* f11* v11*;');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% DELTA CONTROLS%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

f11delta_fcn=['v11deltaf2=str2num(get(h11deltaf2value,''string''));'...
    'v11deltaf1=str2num(get(h11deltaf1value,''string''));'...
    'if v11deltaf2>fs/2;'...
        'msgbox(''A frequência máxima deve ser menor de Fs/2'',''Erro de definição do intervalo de frequência'',''warn'');'...
        'set(h11deltaf2value,''string'',num2str(v11deltaf2ok));'...
        'return;'...
    'end;'...
    'if v11deltaf1<0;'...
        'msgbox(''A frequência mínima deve ser positiva'',''Erro de definição do intervalo de frequência'',''warn'');'...
        'set(h11deltaf1value,''string'',num2str(v11deltaf1ok));'...
        'return;'...
    'end;'...
    'if v11deltaf1>v11deltaf2;'...
        'msgbox(''A frequência máxima deve ser maior do que a mínima'',''Erro de definição do intervalo de frequência'',''warn'');'...
        'set(h11deltaf2value,''string'',num2str(v11deltaf2ok));'...
        'set(h11deltaf1value,''string'',num2str(v11deltaf1ok));'...
        'return;'...
    'end;',...
    'deltaf1=v11deltaf1;'...
    'deltaf2=v11deltaf2;'];

h11deltaframe=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.03,0.82,0.95,0.15]); 

h11deltatxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.031,0.92,0.3,0.04],...
    'fontname','arial',...
    'fontsize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','DELTA [Hz]');

h11deltaf1text=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.1,0.86,0.12,0.035],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Fmin:');

h11deltaf1value=uicontrol('style','edit',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'string',num2str(deltaf1),...
    'backgroundcolor','white',...
    'position',[0.23,0.855,0.2,0.05],...
    'callback',f11delta_fcn);

h11deltaf2text=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.55,0.86,0.12,0.035],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Fmax:');

h11deltaf2value=uicontrol('style','edit',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'string',num2str(deltaf2),...
    'backgroundcolor','white',...
    'position',[0.68,0.855,0.2,0.05],...
    'callback',f11delta_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% THETA CONTROLS%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

f11theta_fcn=['v11thetaf2=str2num(get(h11thetaf2value,''string''));'...
    'v11thetaf1=str2num(get(h11thetaf1value,''string''));'...
    'if v11thetaf2>fs/2;'...
        'msgbox(''A frequência máxima deve ser menor de Fs/2'',''Erro de definição do intervalo de frequência'',''warn'');'...
        'set(h11thetaf2value,''string'',num2str(v11thetaf2ok));'...
        'return;'...
    'end;'...
    'if v11thetaf1<0;'...
        'msgbox(''A frequência mínima deve ser positiva'',''Erro de definição do intervalo de frequência'',''warn'');'...
        'set(h11thetaf1value,''string'',num2str(v11thetaf1ok));'...
        'return;'...
    'end;'...
    'if v11thetaf1>v11thetaf2;'...
        'msgbox(''A frequência máxima deve ser maior do que a mínima'',''Erro de definição do intervalo de frequência'',''warn'');'...
        'set(h11thetaf2value,''string'',num2str(v11thetaf2ok));'...
        'set(h11thetaf1value,''string'',num2str(v11thetaf1ok));'...
        'return;'...
    'end;',...
    'thetaf1=v11thetaf1;'...
    'thetaf2=v11thetaf2;'];

h11thetaframe=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.03,0.65,0.95,0.15]); 

h11thetatxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.031,0.75,0.3,0.04],...
    'fontname','arial',...
    'fontsize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','THETA [Hz]');

h11thetaf1text=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.1,0.69,0.12,0.035],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Fmin:');

h11thetaf1value=uicontrol('style','edit',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'string',num2str(thetaf1),...
    'backgroundcolor','white',...
    'position',[0.23,0.685,0.2,0.05],...
    'callback',f11theta_fcn);

h11thetaf2text=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.55,0.69,0.12,0.035],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Fmax:');

h11thetaf2value=uicontrol('style','edit',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'string',num2str(thetaf2),...
    'backgroundcolor','white',...
    'position',[0.68,0.685,0.2,0.05],...
    'callback',f11theta_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ALPHA CONTROLS%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

f11alpha_fcn=['v11alphaf2=str2num(get(h11alphaf2value,''string''));'...
    'v11alphaf1=str2num(get(h11alphaf1value,''string''));'...
    'if v11alphaf2>fs/2;'...
        'msgbox(''A frequência máxima deve ser menor de Fs/2'',''Erro de definição do intervalo de frequência'',''warn'');'...
        'set(h11alphaf2value,''string'',num2str(v11alphaf2ok));'...
        'return;'...
    'end;'...
    'if v11alphaf1<0;'...
        'msgbox(''A frequência mínima deve ser positiva'',''Erro de definição do intervalo de frequência'',''warn'');'...
        'set(h11alphaf1value,''string'',num2str(v11alphaf1ok));'...
        'return;'...
    'end;'...
    'if v11alphaf1>v11alphaf2;'...
        'msgbox(''A frequência máxima deve ser maior do que a mínima'',''Erro de definição do intervalo de frequência'',''warn'');'...
        'set(h11alphaf2value,''string'',num2str(v11alphaf2ok));'...
        'set(h11alphaf1value,''string'',num2str(v11alphaf1ok));'...
        'return;'...
    'end;',...
    'alphaf1=v11alphaf1;'...
    'alphaf2=v11alphaf2;'];

h11alphaframe=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.03,0.48,0.95,0.15]); 

h11alphatxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.031,0.58,0.3,0.04],...
    'fontname','arial',...
    'fontsize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','ALPHA [Hz]');

h11alphaf1text=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.1,0.52,0.12,0.035],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Fmin:');

h11alphaf1value=uicontrol('style','edit',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'string',num2str(alphaf1),...
    'backgroundcolor','white',...
    'position',[0.23,0.515,0.2,0.05],...
    'callback',f11alpha_fcn);

h11alphaf2text=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.55,0.52,0.12,0.035],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Fmax:');

h11alphaf2value=uicontrol('style','edit',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'string',num2str(alphaf2),...
    'backgroundcolor','white',...
    'position',[0.68,0.515,0.2,0.05],...
    'callback',f11alpha_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% BETHA CONTROLS%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

f11betha_fcn=['v11bethaf2=str2num(get(h11bethaf2value,''string''));'...
    'v11bethaf1=str2num(get(h11bethaf1value,''string''));'...
    'if v11bethaf2>fs/2;'...
        'msgbox(''A frequência máxima deve ser menor de Fs/2'',''Erro de definição do intervalo de frequência'',''warn'');'...
        'set(h11bethaf2value,''string'',num2str(v11bethaf2ok));'...
        'return;'...
    'end;'...
    'if v11bethaf1<0;'...
        'msgbox(''A frequência mínima deve ser positiva'',''Erro de definição do intervalo de frequência'',''warn'');'...
        'set(h11bethaf1value,''string'',num2str(v11bethaf1ok));'...
        'return;'...
    'end;'...
    'if v11bethaf1>v11bethaf2;'...
        'msgbox(''A frequência máxima deve ser maior do que a mínima'',''Erro de definição do intervalo de frequência'',''warn'');'...
        'set(h11bethaf2value,''string'',num2str(v11bethaf2ok));'...
        'set(h11bethaf1value,''string'',num2str(v11bethaf1ok));'...
        'return;'...
    'end;',...
    'bethaf1=v11bethaf1;'...
    'bethaf2=v11bethaf2;'];

h11bethaframe=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.03,0.31,0.95,0.15]); 

h11bethatxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.031,0.41,0.3,0.04],...
    'fontname','arial',...
    'fontsize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','BETHA [Hz]');

h11bethaf1text=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.1,0.35,0.12,0.035],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Fmin:');

h11bethaf1value=uicontrol('style','edit',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'string',num2str(bethaf1),...
    'backgroundcolor','white',...
    'position',[0.23,0.345,0.2,0.05],...
    'callback',f11betha_fcn);

h11bethaf2text=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.55,0.35,0.12,0.035],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Fmax:');

h11bethaf2value=uicontrol('style','edit',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'string',num2str(bethaf2),...
    'backgroundcolor','white',...
    'position',[0.68,0.345,0.2,0.05],...
    'callback',f11betha_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% GAMMA CONTROLS%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

f11gamma_fcn=['v11gammaf2=str2num(get(h11gammaf2value,''string''));'...
    'v11gammaf1=str2num(get(h11gammaf1value,''string''));'...
    'if v11gammaf2>fs/2;'...
        'msgbox(''A frequência máxima deve ser menor de Fs/2'',''Erro de definição do intervalo de frequência'',''warn'');'...
        'set(h11gammaf2value,''string'',num2str(v11gammaf2ok));'...
        'return;'...
    'end;'...
    'if v11gammaf1<0;'...
        'msgbox(''A frequência mínima deve ser positiva'',''Erro de definição do intervalo de frequência'',''warn'');'...
        'set(h11gammaf1value,''string'',num2str(v11gammaf1ok));'...
        'return;'...
    'end;'...
    'if v11gammaf1>v11gammaf2;'...
        'msgbox(''A frequência máxima deve ser maior do que a mínima'',''Erro de definição do intervalo de frequência'',''warn'');'...
        'set(h11gammaf2value,''string'',num2str(v11gammaf2ok));'...
        'set(h11gammaf1value,''string'',num2str(v11gammaf1ok));'...
        'return;'...
    'end;',...
    'gammaf1=v11gammaf1;'...
    'gammaf2=v11gammaf2;'];

h11gammaframe=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.03,0.14,0.95,0.15]); 

h11gammatxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.031,0.24,0.32,0.04],...
    'fontname','arial',...
    'fontsize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','GAMMA [Hz]');

h11gammaf1text=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.1,0.18,0.12,0.035],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Fmin:');

h11gammaf1value=uicontrol('style','edit',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'string',num2str(gammaf1),...
    'backgroundcolor','white',...
    'position',[0.23,0.175,0.2,0.05],...
    'callback',f11gamma_fcn);

h11gammaf2text=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.55,0.18,0.12,0.035],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Fmax:');

h11gammaf2value=uicontrol('style','edit',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'string',num2str(gammaf2),...
    'backgroundcolor','white',...
    'position',[0.68,0.175,0.2,0.05],...
    'callback',f11gamma_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% OK BUTTON%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

f11ok_fcn=['switch calcok;'...
    'case 1;'....
        'disp(''case 1'');'...
        'set(h1alphatxt,''tooltipstring'',strcat(num2str(alphaf1),'':'',num2str(alphaf2),'' [Hz]''));'...
        'set(h1gammatxt,''tooltipstring'',strcat(num2str(gammaf1),'':'',num2str(gammaf2),'' [Hz]''));'...
        'set(h1bethatxt,''tooltipstring'',strcat(num2str(bethaf1),'':'',num2str(bethaf2),'' [Hz]''));'...
        'set(h1thetatxt,''tooltipstring'',strcat(num2str(thetaf1),'':'',num2str(thetaf2),'' [Hz]''));'...
        'set(h1deltatxt,''tooltipstring'',strcat(num2str(deltaf1),'':'',num2str(deltaf2),'' [Hz]''));'...
        'eval(f1calcpot_fcn);'...
    'case 2;'...
        'disp(''case 2'');'...
        'set(h22intpotalfa,''tooltipstring'',strcat(num2str(alphaf1),'':'',num2str(alphaf2),'' [Hz]''));'...
        'set(h22intpotgamma,''tooltipstring'',strcat(num2str(gammaf1),'':'',num2str(gammaf2),'' [Hz]''));'...
        'set(h22intpotbeta,''tooltipstring'',strcat(num2str(bethaf1),'':'',num2str(bethaf2),'' [Hz]''));'...
        'set(h22intpotteta,''tooltipstring'',strcat(num2str(thetaf1),'':'',num2str(thetaf2),'' [Hz]''));'...
        'set(h22intpotdelta,''tooltipstring'',strcat(num2str(deltaf1),'':'',num2str(deltaf2),'' [Hz]''));'...
        'eval(f22calcpot_fcn);'...
    'end;'...
    'close(h11ritconfig);'...
    'clear h11* f11* v11*;'];

h11ok=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.3,0.02,0.4,0.1],...
    'fontname','arial',...
    'fontsize',9,...
    'string','OK',...
    'callback',f11ok_fcn);