% f1tvalue_callback=['v1ampmin=1000000;'...
%         'v1ampmax=0;'...
%         'v1tinicial=str2num(get(h1tinicialvalue,''string''));'...
%         'v1tfinal=str2num(get(h1tfinalvalue,''string''));'...
%         'if v1tfinal>v1treg;'...
%             'msgbox(''O tempo máximo deve ser menor do tempo de registro'',''Erro de definição'',''warn'');'...
%             'set(h1tfinalvalue,''string'',num2str(v1tfinalok));'...
%             'return;'...
%         'end;'...
%         'if v1tfinal<v1tinicial;'...
%             'msgbox(''O tempo máximo deve ser maior do que a mínimo'',''Erro de definição'',''warn'');'...
%             'set(h1tinicialvalue,''string'',num2str(v1tinicialok));'...
%             'set(h1tfinalvalue,''string'',num2str(v1tfinalok));'...
%             'return;'...
%         'end;'...
%         'if v1tinicial<0;'...
%             'msgbox(''O tempo mínimo deve ser positivo'',''Erro de definição'',''warn'');'...
%             'set(h1tinicialvalue,''string'',num2str(v1tinicialok));'...
%             'return;'...
%         'end;'...
%         'v1tpointinicial=round((v1tinicial*fs)+1);'...
%         'v1tpointfinal=round(v1tfinal*fs);'...
%         'v1tpointfinalref=v1tpointfinal;'...
%         'v1jandata=eval(strcat(v1janela,''('',num2str(v1tpointfinal-v1tpointinicial+1),'');''));'...
%         'for i=1:length(v1pt);'...
%             'v1dados=get(v1pt(i),''ydata'');'...
%             'if length(v1dados)<v1tpointfinal;'...
%                 'v1tpointfinalref=length(v1dados);'...
%             'end;'...
%             'v1jandata=eval(strcat(v1janela,''('',num2str(v1tpointfinalref-v1tpointinicial+1),'');''));'...
%             'v1ampmaxtemp=max(v1dados(v1tpointinicial:v1tpointfinalref));'...
%             'v1ampmintemp=min(v1dados(v1tpointinicial:v1tpointfinalref));'...
%             'if v1ampmaxtemp>v1ampmax;'...
%                 'v1ampmax=v1ampmaxtemp;'...
%             'end;'...
%             'if v1ampmintemp<v1ampmin;'...
%                 'v1ampmin=v1ampmintemp;'...
%             'end;'...
%             'v1prenewsignal=eval(v1signalname{i});'...
%             'v1newsignal=((v1prenewsignal+fa)*fb)-fc;'...
%             'v1newfft=fft(v1newsignal(v1tpointinicial:v1tpointfinalref).*v1jandata)./length(v1newsignal(v1tpointinicial:v1tpointfinalref));'...
%             'v1maxspec(i)=max(abs(v1newfft));'...
%             'v1newfaxis=0:fs/(length(v1newsignal(v1tpointinicial:v1tpointfinalref))-1):fs;'...
%             'set(v1p(i),''xdata'',v1newfaxis,''ydata'',abs(v1newfft));'...
%             'axes(h1axesfourier);'...
%             'v1tpointfinalref=v1tpointfinal;'...
%         'end;'...
%         'axis([0 fs/2 0 max(v1maxspec)]);'...
%         'set(h1fminvalue,''string'',''0'');'...
%         'set(h1fmaxvalue,''string'',num2str(fs/2));'...
%         'set(h1adjustfreq,''enable'',''off'');'...
%         'v1newfftind=1;'...
%         'axes(h1axestempo);'...
%         'axis([v1tinicial v1tfinal v1ampmin v1ampmax]);'...
%         'v1tinicialok=v1tinicial;'...
%         'v1tfinalok=v1tfinal;'...
%         'set(h1ajustempo,''enable'',''off'');'];



f1apagar_callback=['v1sindel=get(h1listsignal,''value'');'...
        'delete(v1p(v1sindel));'...
        'v1p(v1sindel)=[];'...
        'if strcmp(get(h1fftmenuvertsin,''checked''),''on'')==1;'...
            'delete(v1pt(v1sindel));'...
            'v1pt(v1sindel)=[];'...
        'end;'...
        'v1numsig=v1numsig-1;'...
        'v1colorindex=v1colormatindex(v1sindel);'...
        'v1colorname{v1colorindex,2}=0;'...
        'v1colormatindex(v1sindel)=[];'...
        'v1signalploted(v1sindel)=[];'...
        'v1signalname(v1sindel)=[];'...
        'v1tregind(v1sindel)=[];'...
        'v1maxsignal(v1sindel)=[];'...
        'v1minsignal(v1sindel)=[];'...
        'v1vaz=isempty(v1signalploted);'...
        'if v1vaz==1;'...
             'set(h1listsignal,''value'',1);'...
             'set(h1listsignal,''string'',''Nenhum'');'...
             'set(h1tempolabel,''string'',''Tempo de registro [s]:'');'...
             'set(h1fourierzoom,''enable'',''off'');'...
             'set(h1fftmenuverzoom,''checked'',''off'');'...
             'set([h1zoombutton h1tempolabel h1popfrec h1fmintext h1fmaxtext h1fminvalue h1fmaxvalue h1apagar h1limpar h1tempolabel],''enable'',''off'');'...
             'set([h1ajustempo h1adjustfreq h1tinicialtext h1tfinaltext h1tinicialvalue h1tfinalvalue h1fftmenuvertsin],''enable'',''off'');'...
             'set([h1calcpot h1potenciatxt h1potsignal h1potinterval h1deltatxt h1thetatxt h1alphatxt h1bethatxt h1gammatxt ],''enable'',''off'');'...
             'axis([0 1 0 1]);'...
        'else;'...
             'v1tregmin=min(v1tregind);'...
             'v1treg=max(v1tregind);'...
             'set(h1listsignal,''value'',1);'...
             'set(h1tempolabel,''string'',strcat(''Tempo de registro [s]:'',num2str(v1tregind(1))));'...
             'set(h1listsignal,''string'',v1signalploted);'...
             'set(h1axesfourier,''ylim'',[min(v1minsignal) max(v1maxsignal)]);'...
             'set(h1axesfourier,''ylim'',[0 max(v1maxspecini)]);'...
        'end;'];

    % f1addsignal_callback=['if v1numsig>7;'...
%             'msgbox(''O numero maximo de sinais simultaneos e 7. Para inserir outro oculte um dos sinais atuais.'',''Numero maximo de sinais apresentados'',''warn'');'...
%             'return;'...
%         'end;'...
%         '[v1signalext,v1filepath]=uigetfile(''*.ascii'',''Escolha o arquivo de registro'');'...
%         'switch ischar(v1signalext);'...
%             'case 0;'...
%                 'return;'...
%         'end;'...
%         'h7msnimport=msgbox(''...importando sinal...'',''Espere'',''warn'');'...
%         'figure(h1fourier);'...
%         'v1file=strcat(v1filepath,v1signalext);'...
%         'load(v1file);'...
%         'v1signalname{v1numsig}=v1signalext(1:length(v1signalext)-6);'...
%         'v1presignal=eval(v1signalname{v1numsig});'...
%         'v1signal=((v1presignal+fa)*fb)-fc;'...
%         'v1faxis=0:fs/(length(v1signal)-1):fs;'...
%         'v1t{v1numsig}=0:1/fs:(length(v1signal)-1)/fs;'...
%         'v1tregind(v1numsig)=round(max(v1t{v1numsig}));'...
%         'v1tregmin=min(v1tregind);'...
%         'v1treg=round(max(v1tregind));'...
%         'v1tregstr=sprintf(''%6.2f'',v1treg);'...
%         'v1tfinalok=str2num(v1tregstr);'...
%         'v1tempotext=strcat(''Tempo de registro [s]: '',v1tregstr);'...
%         'set(h1tempolabel,''enable'',''on'',''string'',v1tempotext);'...
%         'for i=1:7;'...
%             'if v1colorname{i,2}==0;'...
%                 'v1colorstr=v1colorname{i,1};'...
%                 'v1colorname{i,2}=1;'...
%                 'v1colorplot=v1colorname{i,3};'...
%                 'v1colormatindex(v1numsig)=i;'...
%                 'break;'...
%             'end;'...
%         'end;'...
%         'if v1tempind==1;'...
%             'v1tlimits=get(h1axestempo,''xlim'');'...
%             'v1tfinalok=v1tlimits(2);'...
%             'if v1tlimits(2)>v1tregind(v1numsig);'...
%                 'v1tlimits(2)=v1tregind(v1numsig);'...
%             'end;'...
%             'set([h1fftmenuvertsin h1tinicialvalue h1tfinalvalue h1tinicialtext h1tfinaltext],''enable'',''on'');'...
%             'v1signmtxt=v1signalname{v1numsig};'...
%             'v1presignm=eval(v1signmtxt);'...
%             'v1signm=((v1presignm+fa)*fb)-fc;'...
%             'axes(h1axestempo);'...
%             'hold on;'...
%             'v1pt(v1numsig)=plot(v1t{v1numsig},v1signm,v1colorplot);'...
%             'grid on;'...
%             'set(h1axestempo,''xlim'',[v1tlimits(1) v1tfinalok]);'...
%             'v1inflimit=round(v1tlimits(1)*fs+1);'...
%             'v1suplimit=round(v1tlimits(2)*fs);'...
%             'v1jandata=eval(strcat(v1janela,''('',num2str(v1suplimit-v1inflimit+1),'');''));'...
%             'v1signalint=v1signal(v1inflimit:v1suplimit).*v1jandata;'...
%             'v1frecsignal=fft(v1signalint)./length(v1signalint);'...
%             'v1faxis=0:fs/(length(v1signalint)-1):fs;'...
%         'else;'...
%            'set(h1tfinalvalue,''string'',v1tregstr);'...
%             'v1jandata=eval(strcat(v1janela,''('',num2str(length(v1signal)),'');''));'...
%             'v1signal=v1signal.*v1jandata;'...
%             'v1frecsignal=fft(v1signal)./length(v1signal);'...
%             'v1faxis=0:fs/(length(v1signal)-1):fs;'...
%         'end;'...
%         'axes(h1axesfourier);'...
%         'hold on;'...
%         'v1p(v1numsig)=plot(v1faxis,abs(v1frecsignal),v1colorplot);'...
%         'grid on;'...
%         'axis tight;'...
%         'set(h1axesfourier,''xlim'',[str2num(get(h1fminvalue,''string'')) str2num(get(h1fmaxvalue,''string''))]);'...
%         'v1newfftind=0;'...
%         'v1tempind=strcmp(get(h1fftmenuvertsin,''checked''),''on'');'...
%         'v1numsig=v1numsig+1;'...
%         'v1sigtxt=strcat(v1signalname{v1numsig-1},'''',''('',v1colorstr,'')'');'...
%         'v1signalploted{v1numsig-1}=v1sigtxt;'...
%         'set(h1listsignal,''string'',v1signalploted);'...
%         'set(h1popfrec,''enable'',''on'',''value'',1);'...
%         'set([h1fmintext h1fmaxtext h1fminvalue h1fmaxvalue h1fftmenujanela],''enable'',''off'');'...
%         'set(h1fminvalue,''string'',''0'');'...
%         'set(h1fmaxvalue,''string'',num2str(fs/2));'...
%         'delete(h7msnimport);'...
%         'set([h1calcpot h1zoombutton h1fftmenuvertsin h1limpar h1apagar h1fftmenuver h1fftmenuexportar],''enable'',''on'');'];
