
%%%%ESPECTRO DO INTERVALO SFFT%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%FIGURA%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

 h22sfftint=figure('units','normalized',...
    'menubar','none',...
    'resize','off',...
    'numbertitle','off',...
    'color','white',...
    'deletefcn','set(h2espectsignalsfft,''enable'',''on'');',...
    'position',[0.2,0.2,0.5,0.7]);
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% POTENCIA %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h22intpotencia=uicontrol('style','text',...
    'backgroundcolor','white',...
    'visible','off',...
    'units','normalized',...
    'position',[0.05,0.07,0.4,0.03],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Potência dos ritmos no EEG [uW]:');

h22intpotalfa=uicontrol('style','text',...
    'backgroundcolor','white',...
    'visible','off',...
    'units','normalized',...
    'position',[0.42,0.03,0.15,0.03],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'tooltipstring',strcat(num2str(alphaf1),':',num2str(alphaf2),' [Hz]'),...
    'string','Alfa:');

h22intpotbeta=uicontrol('style','text',...
    'backgroundcolor','white',...
    'visible','off',...
    'units','normalized',...
    'position',[0.62,0.03,0.15,0.03],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'tooltipstring',strcat(num2str(bethaf1),':',num2str(bethaf2),' [Hz]'),...
    'string','Beta:');

h22intpotteta=uicontrol('style','text',...
    'backgroundcolor','white',...
    'visible','off',...
    'units','normalized',...
    'position',[0.23,0.03,0.15,0.03],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'tooltipstring',strcat(num2str(thetaf1),':',num2str(thetaf2),' [Hz]'),...
    'string','Teta:');

h22intpotdelta=uicontrol('style','text',...
    'backgroundcolor','white',...
    'visible','off',...
    'units','normalized',...
    'position',[0.05,0.03,0.15,0.03],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'tooltipstring',strcat(num2str(deltaf1),':',num2str(deltaf2),' [Hz]'),...
    'string','Delta:');

h22intpotgamma=uicontrol('style','text',...
    'backgroundcolor','white',...
    'visible','off',...
    'units','normalized',...
    'position',[0.81,0.03,0.2,0.03],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'tooltipstring',strcat(num2str(gammaf1),':',num2str(gammaf2),' [Hz]'),...
    'string','Gamma:');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%MENU%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h22menufigintarq=uimenu('label','Arquivo');

f22salvarfigint_fcn=['[v22file v22path]=uiputfile;'...
    'v22pathfile=strcat(v22path,v22file);'...
    'print(h22sfftint,''-djpeg90'',v22pathfile);'];

h22figintarqsave=uimenu(h22menufigintarq,'label','Salvar figura','callback',f22salvarfigint_fcn);

h22figintarqexpo=uimenu(h22menufigintarq,'label','Exportar dados');
f22figintsair_fcn=['delete( h22sfftint);'...
    'clear  h22*;'];

h22figintarqsair=uimenu(h22menufigintarq,'label','Sair','separator','on','callback',f22figintsair_fcn);

h22menufigintver=uimenu('label','Ver');

f22sfftintverpot_fcn=['v22chkind=strcmp(get(h22figintverpot,''checked''),''on'');'...
    'switch v22chkind;'...
        'case 1;'...
            'set(h22axesintsfft,''position'',[0.1,0.1,0.85,0.85]);'...
            'set([h22intpotencia h22intpotalfa h22intpotbeta h22intpotteta h22intpotdelta h22intpotgamma],''visible'',''off'');'...
            'set(h22figintverpot,''checked'',''off'');'...
        'case 0;'...
            'set(h22axesintsfft,''position'',[0.1,0.2,0.85,0.75]);'...
            'set([h22intpotencia h22intpotalfa h22intpotbeta h22intpotteta h22intpotdelta h22intpotgamma],''visible'',''on'');'...
            'set(h22figintverpot,''checked'',''on'');'...
     'end;'];
    

h22figintverpot=uimenu(h22menufigintver,'label','Potência do espectro','checked','off','callback',f22sfftintverpot_fcn);


f22zoompost_fcn=['v22axeslimits=get(h22axesintsfft,''xlim'');'...
       'if v22axeslimits(1)<v22flimini(1);'...
            'v22axeslimits(1)=v22flimini(1);'...
        'end;'...
        'if v22axeslimits(2)>v22flimini(2);'...
            'v22axeslimits(2)=v22flimini(2);'...
        'end;'...
        'set(h22axesintsfft,''xlim'',v22axeslimits);'...
        'if v2espcont==0;'...
           'v22tlimits=get(h22axesintsfft,''ylim'');'...
           'if v22tlimits(1)<v22tlimini(1);'...
                'v22tlimits(1)=v22tlimini(1);'...
            'end;'...
            'if v22tlimits(2)>v22tlimini(2);'...
                'v22tlimits(2)=v22tlimini(2);'...
            'end;'...
            'set(h22axesintsfft,''ylim'',v22tlimits);'...
        'end;'];

f22zoom_fcn=['v22zoomind=strcmp(get(h22figintverzoom,''checked''),''on'');'...
    'axes(h22axesintsfft);'...
    'switch v22zoomind;'...
        'case 1;'...
            'set(h22zoom,''enable'',''off'');'...
            'set(h22figintverzoom,''checked'',''off'');'...
        'case 0;'...
            'set(h22zoom,''enable'',''on'',''actionpostcallback'',f22zoompost_fcn);'...
            'set(h22figintverzoom,''checked'',''on'');'...
    'end;'];
    
h22zoom=zoom;
h22figintverzoom=uimenu(h22menufigintver,'label','Zoom','checked','off','callback',f22zoom_fcn);

h22sfftmenuconf=uimenu('label','Configuração');

h22sfftritconfig=uimenu(h22sfftmenuconf,'label','Ritmos EEG','callback','ritconfig');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% GRAFICO %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h22axesintsfft=axes('units','normalized',...
    'position',[0.1,0.1,0.85,0.85]);
    axis([0 1 0 1]);

f22calcpot_fcn=['v22specdata=v2freqdata;'...
    'alphaf1p=round(alphaf1*length(v22specdata)/fs);'...
    'alphaf2p=round(alphaf2*length(v22specdata)/fs);'...
    'v22alphapot=0;'...
    'for i=alphaf1p:alphaf2p;'...
        'v22alphapot=v22alphapot+(v22specdata(i).^2)/(2*pi);'...
    'end;'...    
    'set(h22intpotalfa,''string'',strcat(''Alpha:'',num2str(v22alphapot)));'...
    'bethaf1p=round(bethaf1*length(v22specdata)/fs);'...
    'bethaf2p=round(bethaf2*length(v22specdata)/fs);'...
    'v22bethapot=0;'...
    'for i=bethaf1p:bethaf2p;'...
        'v22bethapot=v22bethapot+(v22specdata(i).^2)/(2*pi);'...
    'end;'...    
    'set(h22intpotbeta,''string'',strcat(''Betha:'',num2str(v22bethapot)));'...
    'thetaf1p=round(thetaf1*length(v22specdata)/fs);'...
    'thetaf2p=round(thetaf2*length(v22specdata)/fs);'...
    'v22thetapot=0;'...
    'for i=thetaf1p:thetaf2p;'...
        'v22thetapot=v22thetapot+(v22specdata(i).^2)/(2*pi);'...
    'end;'...    
    'set(h22intpotteta,''string'',strcat(''Theta:'',num2str(v22thetapot)));'...
    'deltaf1p=round(deltaf1*length(v22specdata)/fs);'...
    'deltaf2p=round(deltaf2*length(v22specdata)/fs);'...
    'v22deltapot=0;'...
    'for i=deltaf1p:deltaf2p;'...
        'v22deltapot=v22deltapot+(v22specdata(i).^2)/(2*pi);'...
    'end;'...    
    'set(h22intpotdelta,''string'',strcat(''Delta:'',num2str(v22deltapot)));'...
    'gammaf1p=round(gammaf1*length(v22specdata)/fs);'...
    'gammaf2p=round(gammaf2*length(v22specdata)/fs);'...
    'v22gammapot=0;'...
    'for i=gammaf1p:gammaf2p;'...
        'v22gammapot=v22gammapot+(v22specdata(i).^2)/(2*pi);'...
    'end;'...    
    'set(h22intpotgamma,''string'',strcat(''Gamma:'',num2str(v22gammapot)));'...
    'calcok=2;'];
    
if v2espcont==1
    v22pf=plot(v2faxis(1:length(v2faxis)/2),v2freqdata(1:length(v2faxis)/2));
    ylabel('Potencia');
    xlabel('Frequencia [Hz]');
    set( h22sfftint,'name',v2sfftinttitle);
    eval(f22calcpot_fcn);
else
    v22xlim=get(h2axessfft,'xlim');
    v22ylim=get(h2axessfft,'ylim');
    v22zdata=get(v2s,'zdata');
    v22pf1=find(v2faxis==v22xlim(1));
    v22pf2=find(v2faxis==v22xlim(2));
    v22pt1=find(v2taxis==v22ylim(1));
    v22pt2=find(v2taxis==v22ylim(2));
   contourf(v2faxis(v22pf1(1):v22pf2(1)),v2taxis(v22pt1(1):v22pt2(1)),v22zdata);
    ylabel('Tempo [s]');
    xlabel('Frequencia [Hz]');
    set(h22figintverpot,'enable','off');
    set( h22sfftint,'name','Grafico de contorno');
    colorbar;
end
axis tight
grid on
v22tlimini=get(h22axesintsfft,'ylim');
v22flimini=get(h22axesintsfft,'xlim');




