
%%%MODULO DE SFFT %%%%%%

sfft_enable=1;
v2sind=0;
v2fmaxok=fs/2;
v2fminiok=0;
v2tinicialok=0;
v2cbar=0;
v2errorfile=0;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%PANEL FRONTAL%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h2showsignal=figure('units','normalized',...
    'position',[0.0038,0.0495,0.993,0.89],...
    'menubar','none',...
    'numbertitle','off',...
    'name','Análise SFFT',...
    'color','white',...
    'deletefcn','clear h2* f2* v2*;calcok=0;sfft_enable=0;');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%GRAFICO PRINCIPAL%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h2axessfft=axes('units','normalized',...
    'position',[0.068,0.2,0.7,0.77]);
    axis([0 1 0 1 0 1]);
    grid on;
    xlabel('Freqüência [Hz]');
    ylabel('Tempo [s]');
    zlabel('Potência');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%INFO SIGNAL%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h2frame1=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.815,0.85,0.175,0.12]);  

h2info=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.82,0.935,0.13,0.02],...
    'fontname','arial',...
    'fontsize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','REGISTRO');

h2sfftsiglabel=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.82,0.91,0.15,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Sinal atual: ');

 h2sfftfslabel=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.82,0.885,0.15,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Fs [Hz]: ');

h2sffttimereglabel=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.82,0.86,0.15,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Tempo de registro [s]: ');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%CONFIGURACAO JANELA%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h2frame2=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.815,0.72,0.175,0.12]);  

h2infojanela=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.82,0.81,0.15,0.022],...
    'fontname','arial',...
    'fontsize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','CONFIGURAÇÃO DE JANELA');

v2janelascell={'Hamming','Gausswin','balckman','hanning','kaiser','hann'};

h2sffttipojanpop=uicontrol('style','popup',...
    'enable','off',...
    'backgroundcolor','white',...
    'units','normalized',...
    'position',[0.85,0.78,0.07,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Hamming|Gaussiana|Blackman|Hanning|Kaiser|Hann');

h2sffttipojanlabel=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.82,0.77,0.03,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Tipo : ');

h2sfftamjan=uicontrol('style','edit',...
    'backgroundcolor','white',...
    'enable','off',...
    'units','normalized',...
    'position',[0.89,0.73,0.04,0.03],...
    'fontname','arial',...
    'fontsize',9,...
    'string','10');

h2sffttamjanlabel=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.82,0.73,0.06,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Tamanho [s]: ');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%LIMPAR SINAL%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h2frame6=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.815,0.02,0.175,0.08]);  

f2limparsignalsfft_callback=['v2resetqtn=questdlg(''Deseja reiniciar o modulo?'',''Reiniciar'',''Sim'',''Não'',''Sim'');'...
    'switch strcmp(''Sim'',v2resetqtn);'...
        'case 1;'...
            'delete(v2s);'...
            'axes(h2axessfft);'...
            'axis([0 1 0 1]);'...
            'view([-37.5,30]);'...
            'set([h2calcsfft h2tempoinisfftvalue h2tempofinsfftvalue h2freqinisfftvalue h2freqfinsfftvalue],''enable'',''off'');'...
            'set([h2upsignalsfft h2downsignalsfft h2leftsignalsfft h2rightsignalsfft  h2limparsignalsfft h2espectsignalsfft],''enable'',''off'');'...
            'set(h2tempofinsfftvalue,''string'',''1'');'...
            'set(h2tempoinisfftvalue,''string'',''0'');'...
            'set(h2freqfinsfftvalue,''string'',''1'');'...
            'set(h2freqinisfftvalue,''string'',''0'');',...
            'set(h2menuoptionresetview,''enable'',''off'',''checked'',''on'');'...
            'set(h2sfftsiglabel,''string'',''Sinal atual:'');'...
            'set(h2sffttimereglabel,''string'',''Tempo de registro [s]: '');'...
            'set( h2sfftfslabel,''string'',''Fs [Hz]: '');',...
            'v2intmat=[];'...
            'set(h2intervallist,''value'',1,''string'',''Nenhum'');',...
            'set([h2sfftmenuver h2calcsfft h2sffttipojanpop h2sfftamjan],''enable'',''off'');'...
            'set(h2sfftselectarquivo,''enable'',''on'');'...
            'v2sind=0;'...
            'if v2cbar>0;'...
                'delete(v2cbar);'...
                'v2cbar=0;'...
            'end;'...
      'end;'];

 h2limparsignalsfft=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.865,0.035,0.08,0.045],...
    'fontname','arial',...
    'enable','off',...
    'fontsize',9,...
    'string','Reiniciar',...
    'callback',f2limparsignalsfft_callback);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%CALCULAR SFFT%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


h2frame4=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.815,0.21,0.175,0.295]);  

f2calssft_callback=['h2msncalcular=msgbox(''...calculando transformada...'',''Espere'',''warn'');'...
    'figure(h2showsignal);'...
    'set(h2intervallist,''value'',1);'...
    'set(h2calcsfft,''enable'',''off'');'...
    'v2janelaelement=get(h2sffttipojanpop,''value'');'...
    'v2jantam=str2num(get(h2sfftamjan,''string''));'...
    'switch v2janelaelement;'...
        'case 1;'...
            'v2janela=hamming(v2jantam*fs);'...
        'case 2;'...
            'v2janela=gausswin(v2jantam*fs);'...
        'case 3;'...
            'v2janela=blackman(v2jantam*fs);'...
        'case 4;'...
            'v2janela=hanning(v2jantam*fs);'...
        'case 5;'...
            'v2janela=kaiser(v2jantam*fs);'...
        'case 6;'...
            'v2janela=hann(v2jantam*fs);'...
    'end;'...
    'v2sfft=[];'...
    'if v2sind==1;'...
        'delete(v2s);'...
        'v2faxis=[];'...
        'v2taxis=[];'...
        'v2zsignaldata=[];'...
        'v2intmat=[];'...
    'end;'...
    'v2janamost=round(v2jantam*fs);'...
    'v2intcomple=floor(length(v2signalsfft)/v2janamost);'...
    'v2psfft1=0;'...
    'v2psfft2=v2janamost;'...
    'for i=1:v2intcomple;'...   
        'v2sfft(i,:)=(fft(v2signalsfft(v2psfft1+1:v2psfft2).*v2janela)./length(v2signalsfft(v2psfft1+1:v2psfft2)));'...
        'v2intmat{i}=strcat(num2str(v2psfft1/fs),'':'',num2str(v2psfft2/fs),'' [s]'');'...
        'v2psfft1=v2psfft2;'...
        'v2psfft2=v2psfft2+v2janamost;'...
    'end;'...
    'v2psfft1=0;'...
    'v2psfft2=v2janamost;'...
    'v2sfft=[zeros(1,v2janamost);v2sfft];'...
    'v2sind=1;'...
    'v2taxis=0:v2janamost/fs:v2janamost*(v2intcomple)/fs;'...
    'v2tfinalok=max(v2taxis);'...
    'v2faxis=0:fs/(v2janamost-1):fs;'...
    'axes(h2axessfft);'...
    'set(h2axessfft,''xdir'',''reverse'');'...
    'v2s=surface(v2faxis(1:round(length(v2faxis)/2)),v2taxis,abs(v2sfft(:,1:round(length(v2faxis)/2))));'...
    'v2zsignaldata=get(v2s,''zdata'');'...
    '[v2azs,v2els]=view;'...
    'axis tight;'...
    'set(h2intervallist,''string'',v2intmat);'...
    'set(h2tempofinsfftvalue,''string'',num2str(max(v2taxis)));'...
    'set(h2tempoinisfftvalue,''string'',''0'');'...
    'set(h2freqfinsfftvalue,''string'',num2str(fs/2));'...
    'set(h2freqinisfftvalue,''string'',''0'');'...
    'set([h2viewfreq h2calcsfft h2tempoinisfftvalue h2tempofinsfftvalue h2freqinisfftvalue h2freqfinsfftvalue h2sfftmenuver],''enable'',''on'');'...
    'set([h2verbutton h2upsignalsfft h2downsignalsfft h2leftsignalsfft h2rightsignalsfft  h2limparsignalsfft h2espectsignalsfft],''enable'',''on'');'...
    'set(h2sfftselectarquivo,''enable'',''off'');'...
    'delete(h2msncalcular);'];

h2calcsfft=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.905,0.22,0.08,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Calcular',...
    'callback',f2calssft_callback);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%ROTACAO%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h2frame3=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.815,0.52,0.175,0.19]);  

h2sfftrot=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.82,0.675,0.1,0.022],...
    'fontname','arial',...
    'fontsize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','ROTAÇÃO');

f2upsignalsfft_callback=['v2els=v2els+2;'...
    'view([v2azs v2els]);'...
    'set(h2menuoptionresetview,''checked'',''off'',''enable'',''on'');'];

h2upsignalsfft=uicontrol('style','pushbutton',...
    'enable','off',...
    'units','normalized',...
    'position',[0.885,0.63,0.04,0.04],...
    'fontname','arial',...
    'fontsize',12,...
    'string','+',...
    'callback',f2upsignalsfft_callback);

f2downsignalsfft_callback=['v2els=v2els-2;'...
    'view([v2azs v2els]);'...
    'set(h2menuoptionresetview,''checked'',''off'',''enable'',''on'');'];

h2downsignalsfft=uicontrol('style','pushbutton',...
    'enable','off',...
    'units','normalized',...
    'position',[0.885,0.53,0.04,0.04],...
    'fontname','arial',...
    'fontsize',12,...
    'string','-',...
    'callback',f2downsignalsfft_callback);

f2leftsignalsfft_callback=['v2azs=v2azs+2;'...
    'view([v2azs v2els]);'...
    'set(h2menuoptionresetview,''checked'',''off'',''enable'',''on'');'];

h2leftsignalsfft=uicontrol('style','pushbutton',...
    'enable','off',...
    'units','normalized',...
    'position',[0.845,0.58,0.04,0.04],...
    'fontname','arial',...
    'fontsize',12,...
    'string','-',...
    'callback',f2leftsignalsfft_callback);

f2rightsignalsfft_callback=['v2azs=v2azs-2;'...
    'view([v2azs v2els]);'...
    'set(h2menuoptionresetview,''checked'',''off'',''enable'',''on'');'];

h2rightsignalsfft=uicontrol('style','pushbutton',...
    'enable','off',...
    'units','normalized',...
    'position',[0.925,0.58,0.04,0.04],...
    'fontname','arial',...
    'fontsize',12,...
    'string','+',...
    'callback',f2rightsignalsfft_callback);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%AJUSTE DE ESCALA %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h2frame5=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.12,0.03,0.49,0.08]);  


f2editscale_callback='set( h2scalesfftadjust,''enable'',''on'')';

f2scalesfftadj_callback=['v2tinicial=str2num(get(h2tempoinisfftvalue,''string''));'...
    'if v2tinicial<0;'...
        'beep;'...
        'msgbox(''O tempo mínimo deve ser positivo'',''Erro de definição'',''warn'');'...
        'set(h2tempoinisfftvalue,''string'',num2str(v2tinicialok));'...
        'return;'...
    'end;'...
    'v2tfinal=str2num(get(h2tempofinsfftvalue,''string''));'...
    'if v2tfinal>v2tregtime;'...
        'beep;'...
        'msgbox(''O tempo máximo deve ser menor do tempo maximo calculado'',''Erro de definição'',''warn'');'...
        'set(h2tempofinsfftvalue,''string'',num2str(v2tfinalok));'...
        'return;'...
    'end;'...
    'if v2tfinal<v2tinicial;'...
        'beep;'...
        'msgbox(''O tempo máximo deve ser maior do que a mínimo'',''Erro de definição'',''warn'');'...
        'set(h2tempoinisfftvalue,''string'',num2str(v2tinicialok));'...
        'set(h2tempofinsfftvalue,''string'',num2str(v2tfinalok));'...
        'return;'...
    'end;'...
    'v2finicial=str2num(get(h2freqinisfftvalue,''string''))+1;'...
    'v2ffinal=str2num(get(h2freqfinsfftvalue,''string''));'...
    'if v2ffinal>fs/2;'...
        'beep;'...
        'msgbox(''A frequência máxima deve ser menor de Fs/2'',''Erro de definição'',''warn'');'...
        'set(h2freqfinsfftvalue,''string'',num2str(v2fmaxok));'...
        'return;'...
    'end;'...
    'if v2ffinal<v2finicial;'...
        'beep;'...
        'msgbox(''A frequência máxima deve ser maior do que a mínima'',''Erro de definição'',''warn'');'...
        'set(h2freqfinsfftvalue,''string'',num2str(v2fmaxok));'...
        'set(h2freqinisfftvalue,''string'',num2str(v2fminiok-1));'...
        'return;'...
    'end;'...
    'if v2finicial<0;'...
        'beep;'...
        'msgbox(''A frequência mínima deve ser positiva'',''Erro de definição do intervalo de frequência'',''warn'');'...
        'set(h2freqinisfftvalue,''string'',num2str(v2fminiok-1));'...
        'return;'...
    'end;'...
    'v2tinicialok=v2tinicial;'...
    'v2tfinalok=v2tfinal;'...
    'v2fmaxok=v2ffinal;'...
    'v2fminiok=v2finicial;'...
    'v2tpontoinicial=round(v2tinicial/str2num(get(h2sfftamjan,''string'')))+1;'...
    'v2tpontofinal=ceil(v2tfinal/str2num(get(h2sfftamjan,''string'')));'...
    'v2fpontoinicial=round(v2finicial*length(v2faxis)/fs);'...
    'v2fpontofinal=ceil(v2ffinal*length(v2faxis)/fs);'...
    'delete(v2s);'...
    'v2s=surface(v2faxis(v2fpontoinicial:v2fpontofinal),v2taxis(v2tpontoinicial:v2tpontofinal),v2zsignaldata(v2tpontoinicial:v2tpontofinal,v2fpontoinicial:v2fpontofinal));'...
    'axis tight;'...
    'set( h2scalesfftadjust,''enable'',''off'');',...
    'set(h2menuoptionresetview,''enable'',''on'',''checked'',''off'');'];

 h2scalesfftadjust=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.335,0.042,0.07,0.05],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Ajustar',...
    'callback',f2scalesfftadj_callback);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%AJUSTE DE ESCALA TEMPO%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h2sffttimescale=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.13,0.08,0.12,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','Escala de tempo [s]');

h2tempoinisfftext=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.13,0.043,0.04,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Tinicial: ');

h2tempoinisfftvalue=uicontrol('style','edit',...
    'units','normalized',...
    'enable','off',...
    'fontname','arial',...
    'fontsize',9,...
    'string','0',...
    'backgroundcolor','white',...
    'position',[0.17,0.04,0.04,0.028],...
    'callback',f2editscale_callback);

h2tempofinfftext=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.22,0.043,0.03,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Tfinal: ');

h2tempofinsfftvalue=uicontrol('style','edit',...
    'units','normalized',...
    'enable','off',...
    'fontname','arial',...
    'fontsize',9,...
    'string','0',...
    'backgroundcolor','white',...
    'position',[0.25,0.04,0.04,0.028],...
    'callback',f2editscale_callback);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%AJUSTE DE ESCALA FREQUENCIA%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h2sfftfreqscale=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.445,0.08,0.13,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','Escala em freqüência [Hz]');

h2freqinisfftext=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.445,0.043,0.034,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Finicial: ');

h2freqinisfftvalue=uicontrol('style','edit',...
    'units','normalized',...
    'enable','off',...
    'fontname','arial',...
    'fontsize',9,...
    'string','0',...
    'backgroundcolor','white',...
    'position',[0.48,0.04,0.04,0.028],...
    'callback',f2editscale_callback);

 h2freqfinsfftext=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.53,0.043,0.03,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Ffinal: ');

h2freqfinsfftvalue=uicontrol('style','edit',...
    'units','normalized',...
    'enable','off',...
    'fontname','arial',...
    'fontsize',9,...
    'string','0',...
    'backgroundcolor','white',...
    'position',[0.56,0.04,0.04,0.028],...
    'callback',f2editscale_callback);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%VISUALIZAR INTERVALO clear%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h2sffintervalos=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.82,0.475,0.1,0.02],...
    'fontname','arial',...
    'fontsize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','INTERVALOS');

h2intervallist=uicontrol('style','listbox',...
    'units','normalized',...
    'position',[0.825,0.275,0.15,0.19],...
    'backgroundcolor','white',...
    'string','Nenhum');

f2verespectro_fcn=['v2interval=get(h2intervallist,''value'');'...
    'v2espcont=1;'...
    'v2freqdata=abs(v2sfft(v2interval+1,:));'...
    'v2sfftinttitle=strcat(''Espectro do intervalo_'',v2intmat{v2interval});'...
    'set(h2espectsignalsfft,''enable'',''off'');'...
    'sfftinterval;'];

h2espectsignalsfft=uicontrol('style','pushbutton',...
    'enable','off',...
    'units','normalized',...
    'position',[0.82,0.22,0.08,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'string','Espectro',...
    'callback',f2verespectro_fcn);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%VISUALIZAR FREQUENCIA%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h2frame7=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.815,0.115,0.175,0.085]);  

 h2freqview=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.825,0.17,0.08,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Frequencia [Hz]');

h2viewfreq=uicontrol('style','edit',...
    'units','normalized',...
    'enable','off',...
    'fontname','arial',...
    'fontsize',9,...
    'string','0',...
    'backgroundcolor','white',...
    'position',[0.84,0.135,0.04,0.028]);

h2verbutton=uicontrol('style','pushbutton',...
    'enable','off',...
    'units','normalized',...
    'position',[0.9,0.135,0.08,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'string','Ver');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% MENU %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

f2errorsignal_fcn=['beep;'...
        'msgbox(''O arquivo nao tem formato compativel'',''Arquivo invalido'',''warn'');'...
        'v2errorfile=1;'];
    
f2selectsignal_callback=['[v2filesfftext,v2pathsfft]=uigetfile(''*.ascii'',''Escolha o arquivo de registro'');'...
        'switch ischar(v2filesfftext);'...
            'case 0;'...
                'return;'...
        'end;'...
        'v2filesfft=strcat(v2pathsfft,v2filesfftext);'...
        'eval(''load(v2filesfft)'',f2errorsignal_fcn);'...
        'if v2errorfile==1;'...
            'v2errorfile=0;'...
            'return;'...
        'end;'...
        'v2signalnamesfft=v2filesfftext(1:length(v2filesfftext)-6);'...
        'set(h2sfftsiglabel,''string'',strcat(''Sinal atual: '',v2signalnamesfft));'...
        'v2signalsfft=((eval(v2signalnamesfft)+fa)*fb)-fc;'...
        'v2t=0:1/fs:(length(v2signalsfft)-1)/fs;'...
        'v2tregtime=round(max(v2t));'...
        'set(h2sffttimereglabel,''string'',strcat(''Tempo de registro [s]: '',num2str(v2tregtime)));'...
        'set( h2sfftfslabel,''string'',strcat(''Fs [Hz]: '',num2str(fs)));'...
        'set([h2calcsfft h2sffttipojanpop h2sfftamjan],''enable'',''on'');'];
    
h2sfftmenuarquivo=uimenu('label','Arquivo');

h2sfftselectarquivo=uimenu(h2sfftmenuarquivo,'label','Selecionar Registro','callback',f2selectsignal_callback);

f2sfftsair_callback=['v2sairqtn=questdlg(''Deseja fechar o modulo?'',''Reiniciar'',''Sim'',''Não'',''Sim'');'...
    'switch strcmp(''Sim'',v2sairqtn);'...
        'case 1;'...
        'close(h2showsignal);'...
        'clear h2* f2* v2*;'...
        'calcok=0;'...
        'sfft_enable=0;'...
    'end;']; 

h2sfftsair=uimenu(h2sfftmenuarquivo,'label','Sair',...
    'separator','on',...
    'callback',f2sfftsair_callback);

h2sfftmenuver=uimenu('label','Ver','enable','off');

f2contorno_fcn=['v2espcont=0;'...
    'sfftinterval;'];

h2menuvercontorno=uimenu(h2sfftmenuver,'label','Contorno','callback',f2contorno_fcn);

f2menucolorbar_callback=['v2checkvalue=get(h2menuoptioncolorbar,''checked'');'...
    'v2checkcmp=strcmp(v2checkvalue,''on'');'...
    'switch v2checkcmp;'...
        'case 1;'...
            'delete(v2cbar);'...
            'set(h2menuoptioncolorbar,''checked'',''off'');'...
            'v2cbar=0;'...
        'case 0;'...
            'v2cbar=colorbar(''eastoutside'');'...
            'set(h2menuoptioncolorbar,''checked'',''on'');'...
    'end;'];

h2menuoptioncolorbar=uimenu(h2sfftmenuver,'label','Colorbar','callback',f2menucolorbar_callback);

f2menuoptionresetview_callback=['delete(v2s);'...
    'v2s=surface(v2faxis(1:round(length(v2faxis)/2)),v2taxis,abs(v2sfft(:,1:round(length(v2faxis)/2))));'...
    'v2zsignaldata=get(v2s,''zdata'');'...
    'view([-37.5,30]);'...
    'axis tight;'...
    'set(h2tempofinsfftvalue,''string'',num2str(max(v2taxis)));'...
    'set(h2tempoinisfftvalue,''string'',''0'');'...
    'set(h2freqfinsfftvalue,''string'',num2str(fs/2));'...
    'set(h2freqinisfftvalue,''string'',''0'');',...
    'set(h2menuoptionresetview,''enable'',''off'',''checked'',''on'');'];

h2menuoptionresetview=uimenu(h2sfftmenuver,'label','Vista original','checked','on','enable','off',...
    'callback',f2menuoptionresetview_callback);

h2sfftmenuexport=uimenu('label','Exportar','enable','off');

h2sfftexportfigura=uimenu(h2sfftmenuexport,'label','Figura(s)');

h2sfftexportmatrixsfft=uimenu(h2sfftmenuexport,'label','Matriz SFFT');

h2sfftexportmatrixfft=uimenu(h2sfftmenuexport,'label','Matriz FFT');



