
%TSST Aplication module%

close
clc

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%INITIAL VALUES%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fa=4096;
% fb=0.0610426077402027;
% fc=250;
% fs=128;

result=[];
keyref=0;
pd=0;
tr=0;
last=0;
e=0;
nnum=0;
errmat=[0 0 0];
tb=0;
wwhite=0;
kref=0;
d=1;
n='';
nd=2;
valini=200;
valinitext=num2str(valini);
digres=7;
digrestext=num2str(digres);
temptest=15;
temptestex=num2str(temptest);
% userdata{1}='\n';
% userdata{2}='\n';
% userdata{3}='\n';
% userdata{4}='200';
% userdata{5}='7';
% userdata{6}='15';
% deltaf1=1;
% deltaf2=3;
% thetaf1=3.5;
% thetaf2=7.5;
% alphaf1=8;
% alphaf2=13;
% bethaf1=14;
% bethaf2=26;
% gammaf1=26;
% gammaf2=100;
% calcok=0;

compmatrix(1)=valini;
for i=2:200
    compmatrix(i)=compmatrix(i-1)-digres;
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%FRONTAL PANEL%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

hf=figure('units','normalized',...
    'position',[0.0038,0.0495,0.993,0.89],...
    'menubar','none',...
    'numbertitle','off',...
    'name','Modulo TSST',...
    'color','white',...
    'deletefcn','clear;clc');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%DISPLAY MSG%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
hnum=uicontrol('style','text',...
    'backgroundcolor','white',...
    'units','normalized',...
    'position',[0,0.5,1,0.12],...
    'fontname','arial',...
    'fontsize',50,...
    'foreground','blue',...
    'string','MODULO TSST');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%CAPTURE FUNCTION%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

capture_fcn=['numref=0;'...
    'if pd==1;'...
        'tb=toc;'...
        'set(hnum,''visible'',''off'');'...
        'pd=0;'...
    'end;'...
    'if keyref==14;'...
        'tb=toc;'...
    'end;'...
    'set(hnum,''visible'',''off'');'...
    'key=get(hf,''currentcharacter'');'...
    'keyref=key+1;'...
    'if 49<=keyref;'...
        'if keyref<=58;'...
            'numref=1;'...
        'end;'...
    'end;'...
    'switch numref;'...
        'case 1;'...
            'if wwhite==1;'...
                'set(hf,''color'',''white'');'...
            'end;'...
            'n(d)=key;'...
            'd=d+1;'...
        'otherwise;'...
            'switch keyref;'...
                'case 14;'...
                    'nnum=str2num(n);'...
                    'if tr==0;'...
                        'result(nd,1)=nnum;'...
                        'result(nd,2)=compmatrix(nd-e);'...
                        'result(nd,3)=toc-tb;'...
                        'result(nd,4)=tb-result(nd-1,5);'...
                        'result(nd,5)=toc;'...
                    'else;'...
                        'nerror=last;'...
                    'end;'...
                    'if nnum==compmatrix(nd-e);'...
                        'set(hnum,''visible'',''off'');'...
                        'set(hf,''color'',[0,1,0.5]);'...
                    'else;'...
                        'set(hf,''keypressfcn'',beep);'...
                        'e=e+1;'...
                        'if tr==0;'...
                            'result(nd,6)=1;'...
                            'nerror=num2str(compmatrix(nd-e));'...
                        'else;'...
                            'nerror=num2str(compmatrix(nd-e));'...
                        'end;'...
                        'set(hf,''color'',''red'');'...
                        'set(hnum,''visible'',''on'',''foreground'',''black'',''backgroundcolor'',''red'',''string'',''ERRO!!'');'...
                        'for i=1:10;'...
                            'if tstop==1;'...
                                'set(hf,''color'',''white'');'...
                                'set(hnum,''visible'',''off'');'...
                                'set(hnum, ''backgroundcolor'',''white'',''foreground'',''blue'',''fontsize'',30,''string'',''Fim do Treino'');'...
                                'set(hnum,''visible'',''on'');'...
                                'return;'...
                            'end;'...
                            'beep;'...
                            'set(hnum,''string'','''');'...
                            'pause(0.05);'...
                            'set(hnum,''string'',''ERRO!!'');'...
                            'pause(0.05);'...
                        'end;'...
                         'set(hnum,''string'','''');'...
                        'set(hf,''color'',''white'');'...
                        'set(hnum,''foreground'',''black'',''backgroundcolor'',''white'',''string'',nerror);'...
                        'd=1;'...
                        'set(hf,''keypressfcn'',capture_fcn);'...
                    'end;'...
                    'nd=nd+1;'...
                    'd=1;'...
                'case 33;'...
                    'n='''';'...
                    'd=1;'...
                'case 9;'...
                    'n='''';'...
                    'd=1;'...
                'otherwise;'...
                    'beep;'...
            'end;'...
    'end;'];
    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%MENU%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


htsstmenuarquivo=uimenu('label','Arquivo');
htsstresultadosexportar=uimenu(htsstmenuarquivo,'label','Exportar último teste','enable','off','callback','exportar');
htsstmenusair=uimenu(htsstmenuarquivo,'label','Sair','separator','on','callback','close all;clear all;clc');

iniciar_fcn=['keyini=get(hf,''currentcharacter'');'...
    'keyiniref=keyini+1;'...
    'if keyiniref==14;'...
        'set([htsstmenuarquivo htsstmenutreino htsstmenuteste],''enable'',''off'');'...
        'numinicio=num2str(valini);'...
        'set(hnum,''string'',numinicio,''fontsize'',50,''foreground'',''black'');'...
        'set(hf,''color'',''white'');'...
        'pd=1;'...
        'e=0;'...
        'd=1;'...
        'n='''';'...
        'nd=2;'...
        'result=[];'...
        'result(1,1)=valini;'...
        'result(1,6)=0;'...
        'set(htimer,''period'',temptest);'...
        'start(htimer);'...
        'tsstclock=clock;'...
        'tic;'...
        'set(hf,''keypressfcn'',capture_fcn);'...
    'else;'...
        'beep;'...
    'end;'];

htsstmenutreino=uimenu('label','Treino');
htreinoconfig=uimenu(htsstmenutreino,'label','Configurar Treino','callback','tr=1;configuracion');
htreinoiniciar_callback=['tr=1;'...
         'msgbox(''Lembre-se de configurar o treino! Se já o fez ignore esta mensagem'',''Sugestão'',''warn'');'...
         'set(hnum,''fontsize'',30,''string'',''Para começar o treino digite Enter'');'...
         'tstop=0;'...
         'set(hf,''keypressfcn'',iniciar_fcn);'];
htreinoiniciar=uimenu(htsstmenutreino,'label','Iniciar Treino','callback',htreinoiniciar_callback);


htsstmenuteste=uimenu('label','Teste');
htesteconfig=uimenu(htsstmenuteste,'label','Configurar Teste','callback','tr=0;configuracion');
huserconfig=uimenu(htsstmenuteste,'label','Configurar Usuário','callback','userconfig');


hmenuinicioteste_callback=['tr=0;'...
        'msgbox(''Lembre-se de configurar o teste! Se já o fez ignore esta mensagem'',''Sugestão'',''warn'');'...
        'set(hf,''color'',''white'');'...
        'set(hnum,''fontsize'',30);'...
        'tstop=0;'...
        'set(hnum,''string'',''Para começar o teste digite Enter'');'...
        'set(hf,''keypressfcn'',iniciar_fcn);'];

hmenuinicioteste=uimenu(htsstmenuteste,'label','Iniciar Teste','enable','off','callback',hmenuinicioteste_callback,'separator','on');

htsstmenuanalise=uimenu('label','Analise');
hmenuanaliseedit=uimenu(htsstmenuanalise,'label','Editar registro','callback','editionmodule');
hmenuanalisetempo=uimenu(htsstmenuanalise,'label','Tempo','callback','timemodule','separator','on');
hmenuanalisefourier=uimenu(htsstmenuanalise,'label','Fourier','callback','fouriermodule');
hmenuanalisesfft=uimenu(htsstmenuanalise,'label','SFFT','callback','sfftmodule');
hmenuanalisewave=uimenu(htsstmenuanalise,'label','Wavelets');
hmenuanaliseconfig=uimenu(htsstmenuanalise,'label','Configuração Análise','separator','on','callback','regconfig');
   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%TIMER%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  
 htimer_fcn=['tstop=1;'...
       'set(hf,''color'',''white'');'...
       'taex=get(htimer,''tasksexecuted'');'...
       'if taex==2;'...
            'set(hnum,''visible'',''off'');'...
            'set(hf,''keypressfcn'',''beep'',''color'',''black'');'...
            'if tr==0;'...
                'ex=questdlg(''Deseja exportar os dados?'',''Fim do Teste'',''Sim'',''Não'',''Sim'');'...
                'exind=strcmp(ex,''Sim'');'...
                'set(hf,''color'',''white'');'...
                'set(hnum,''string'',''Fim do Teste'',''visible'',''on'',''foreground'',''blue'');'...
                'if exind==1;'...
                    'exportar;'...
                'end;'...
                'msgbox(''Fim do teste'',''Obrigado!'',''help'');'...
            'else;'...
                'continuar=questdlg(''Deseja treinar de novo?'',''Fim de Treino'',''Sim'',''Não'',''Sim'');'...
                'contind=strcmp(continuar,''Sim'');'...
                'set(hf,''color'',''white'');'...
                'set(hnum,''visible'',''on'',''foreground'',''blue'');'...
                'if contind==1;'...
                    'tstop=0;'...
                    'eval(htreinoiniciar_callback);'...
                'else;'...
                    'set(hnum,''string'',''fontsize'',30,''Fim do Treino'');'...
                'end;'...
            'end;'...
            'set([htsstmenuarquivo htsstresultadosexportar htsstmenutreino htsstmenuteste],''enable'',''on'');'...
       'end;'];
   
 htimer=timer('period',temptest,...
    'executionmode','fixeddelay',...
    'taskstoexecute',2,...
    'stopfcn',htimer_fcn,...
    'timerfcn','t=1;');

    
