
%TSST Aplication module%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%INITIAL VALUES%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
tsst_enable=1;

vtsst_result=[];
vtsst_keyref=0;
vtsst_pd=0;
vtsst_tr=0;
vtsst_last=0;
vtsst_e=0;
vtsst_nnum=0;
vtsst_errmat=[0 0 0];
vtsst_tb=0;
vtsst_wwhite=0;
vtsst_kref=0; %%%%%%%%%%%%%%%%%%%%%%%
vtsst_d=1;
vtsst_n='';
vtsst_nd=2;
vtsst_valini=200;
vtsst_valinitext=num2str(vtsst_valini);
vtsst_digres=7;
vtsst_digrestext=num2str(vtsst_digres);
vtsst_temptest=60;
vtsst_temptestex=num2str(vtsst_temptest);%%%%%%%%%%%%%%%%

vtsst_compmatrix(1)=vtsst_valini;
for i=2:200
    vtsst_compmatrix(i)=vtsst_compmatrix(i-1)-vtsst_digres;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%FRONTAL PANEL%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

htsst_f=figure('units','normalized',...
    'position',[0.0038,0.0495,0.993,0.89],...
    'menubar','none',...
    'numbertitle','off',...
    'name','Modulo TSST',...
    'color','white',...
    'deletefcn','clear htsst* ftsst* vtsst*;tsst_enable=0;');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%DISPLAY MSG%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
htsst_num=uicontrol('style','text',...
    'backgroundcolor','white',...
    'units','normalized',...
    'position',[0,0.5,1,0.12],...
    'fontname','arial',...
    'fontsize',50,...
    'foreground','blue',...
    'string','MODULO TSST');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%CAPTURE FUNCTION%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

ftsst_capture_fcn=['vtsst_numref=0;'...
    'if vtsst_pd==1;'...
        'vtsst_tb=toc;'...
        'set(htsst_num,''visible'',''off'');'...
        'vtsst_pd=0;'...
    'end;'...
    'if vtsst_keyref==14;'...
        'vtsst_tb=toc;'...
    'end;'...
    'set(htsst_num,''visible'',''off'');'...
    'vtsst_key=get(htsst_f,''currentcharacter'');'...
    'vtsst_keyref=vtsst_key+1;'...
    'if 49<=vtsst_keyref;'...
        'if vtsst_keyref<=58;'...
            'vtsst_numref=1;'...
        'end;'...
    'end;'...
    'switch vtsst_numref;'...
        'case 1;'...
            'if vtsst_wwhite==1;'...
                'set(htsst_f,''color'',''white'');'...
            'end;'...
            'vtsst_n(vtsst_d)=vtsst_key;'...
            'vtsst_d=vtsst_d+1;'...
        'otherwise;'...
            'switch vtsst_keyref;'...
                'case 14;'...
                    'vtsst_nnum=str2num(vtsst_n);'...
                    'vtsst_n='''';'...
                    'if vtsst_tr==0;'...
                        'vtsst_result(vtsst_nd,1)=vtsst_nnum;'...
                        'vtsst_result(vtsst_nd,2)=vtsst_compmatrix(vtsst_nd-vtsst_e);'...
                        'vtsst_result(vtsst_nd,3)=toc-vtsst_tb;'...
                        'vtsst_result(vtsst_nd,4)=vtsst_tb-vtsst_result(vtsst_nd-1,5);'...
                        'vtsst_result(vtsst_nd,5)=toc;'...
                    'else;'...
                        'vtsst_nerror=vtsst_last;'...
                    'end;'...
                    'if vtsst_nnum==vtsst_compmatrix(vtsst_nd-vtsst_e);'...
                        'set(htsst_num,''visible'',''off'');'...
                        'set(htsst_f,''color'',[0,1,0.5]);'...
                    'else;'...
                        'set(htsst_f,''keypressfcn'',beep);'...
                        'vtsst_e=vtsst_e+1;'...
                        'if vtsst_tr==0;'...
                            'vtsst_result(vtsst_nd,6)=1;'...
                            'vtsst_nerror=num2str(vtsst_compmatrix(vtsst_nd-vtsst_e));'...
                        'else;'...
                            'vtsst_nerror=num2str(vtsst_compmatrix(vtsst_nd-vtsst_e));'...
                        'end;'...
                        'set(htsst_f,''color'',''red'');'...
                        'set(htsst_num,''visible'',''on'',''foreground'',''black'',''backgroundcolor'',''red'',''string'',''ERRO!!'');'...
                        'for i=1:10;'...
                            'if vtsst_tstop==1;'...
                                'set(htsst_f,''color'',''white'');'...
                                'set(htsst_num,''visible'',''off'');'...
                                'if vtsst_tr==0;'...
                                    'set(htsst_num, ''backgroundcolor'',''white'',''foreground'',''blue'',''fontsize'',30,''string'',''Fim do Treino'');'...
                                'else;'...
                                    'set(htsst_num, ''backgroundcolor'',''white'',''foreground'',''blue'',''fontsize'',30,''string'',''Fim do Teste'');'...
                                'end;'...
                                'set(htsst_num,''visible'',''on'');'...
                                'return;'...
                            'end;'...
                            'beep;'...
                            'set(htsst_num,''string'','''');'...
                            'pause(0.05);'...
                            'set(htsst_num,''string'',''ERRO!!'');'...
                            'pause(0.05);'...
                        'end;'...
                        'set(htsst_num,''string'','''');'...
                        'set(htsst_f,''color'',''white'');'...
                        'set(htsst_num,''foreground'',''black'',''backgroundcolor'',''white'',''string'',vtsst_nerror);'...
                        'vtsst_d=1;'...
                        'set(htsst_f,''keypressfcn'',ftsst_capture_fcn);'...
                    'end;'...
                    'vtsst_nd=vtsst_nd+1;'...
                    'vtsst_d=1;'...
                'case 33;'...
                    'vtsst_n='''';'...
                    'vtsst_d=1;'...
                'case 9;'...
                    'vtsst_n='''';'...
                    'vtsst_d=1;'...
                'otherwise;'...
                    'beep;'...
            'end;'...
    'end;'];
    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%MENU%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


htsstmenuarquivo=uimenu('label','Arquivo');
htsstresultadosexportar=uimenu(htsstmenuarquivo,'label','Exportar último teste','enable','off','callback','exportar');
htsstmenusair=uimenu(htsstmenuarquivo,'label','Sair','separator','on','callback','close all;clear htsst* vtsst* ftsst*;tsst_enable=0;');

ftsst_iniciar_fcn=['vtsst_keyini=get(htsst_f,''currentcharacter'');'...
    'vtsst_keyiniref=vtsst_keyini+1;'...
    'if vtsst_keyiniref==14;'...
        'set([htsstmenuarquivo htsstmenutreino htsstmenuteste],''enable'',''off'');'...
        'vtsst_numinicio=num2str(vtsst_valini);'...
        'set(htsst_num,''string'',vtsst_numinicio,''fontsize'',50,''foreground'',''black'');'...
        'set(htsst_f,''color'',''white'');'...
        'vtsst_pd=1;'...
        'vtsst_e=0;'...
        'vtsst_d=1;'...
        'vtsst_n='''';'...
        'vtsst_nd=2;'...
        'vtsst_result=[];'...
        'vtsst_result(1,1)=vtsst_valini;'...
        'vtsst_result(1,6)=0;'...
        'set(htsst_timer,''period'',vtsst_temptest);'...
        'start(htsst_timer);'...
        'vtsst_clock=clock;'...
        'tic;'...
        'set(htsst_f,''keypressfcn'',ftsst_capture_fcn);'...
    'else;'...
        'beep;'...
    'end;'];

htsstmenutreino=uimenu('label','Treino');
htssttreinoconfig=uimenu(htsstmenutreino,'label','Configurar Treino','callback','vtsst_tr=1;configuracion');
ftsst_treinoiniciar_fcn=['vtsst_tr=1;'...
         'msgbox(''Lembre-se de configurar o treino! Se já o fez ignore esta mensagem'',''Sugestão'',''warn'');'...
         'set(htsst_num,''fontsize'',30,''string'',''Para começar o treino digite Enter'');'...
         'vtsst_tstop=0;'...
         'set(htsst_f,''keypressfcn'',ftsst_iniciar_fcn);'];
htsst_treinoiniciar=uimenu(htsstmenutreino,'label','Iniciar Treino','callback',ftsst_treinoiniciar_fcn);


htsstmenuteste=uimenu('label','Teste');
htsst_testeconfig=uimenu(htsstmenuteste,'label','Configurar Teste','callback','vtsst_tr=0;configuracion');
htsst_userconfig=uimenu(htsstmenuteste,'label','Configurar Usuário','callback','userconfig');


ftsst_hmenuinicioteste_fcn=['vtsst_tr=0;'...
        'msgbox(''Lembre-se de configurar o teste! Se já o fez ignore esta mensagem'',''Sugestão'',''warn'');'...
        'set(htsst_f,''color'',''white'');'...
        'set(htsst_num,''fontsize'',30);'...
        'vtsst_tstop=0;'...
        'set(htsst_num,''string'',''Para começar o teste digite Enter'');'...
        'set(htsst_f,''keypressfcn'',ftsst_iniciar_fcn);'];

switch userok
    case 1
        vtsst_intest='on';
    case 0
        vtsst_intest='off';
end

htsst_menuinicioteste=uimenu(htsstmenuteste,'label','Iniciar Teste','enable',vtsst_intest,'callback',ftsst_hmenuinicioteste_fcn,'separator','on');

  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%TIMER%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  
 ftsst_timer_fcn=['vtsst_tstop=1;'...
       'set(htsst_f,''color'',''white'');'...
       'vtsst_taex=get(htsst_timer,''tasksexecuted'');'...
       'if vtsst_taex==2;'...
            'set(htsst_num,''visible'',''off'');'...
            'set(htsst_f,''keypressfcn'',''beep'',''color'',''black'');'...
            'if vtsst_tr==0;'...
                'vtsst_ex=questdlg(''Deseja exportar os dados?'',''Fim do Teste'',''Sim'',''Não'',''Sim'');'...
                'vtsst_exind=strcmp(vtsst_ex,''Sim'');'...
                'set(htsst_f,''color'',''white'');'...
                'set(htsst_num,''string'',''Fim do Teste'',''fontsize'',30,''backgroundcolor'',''white'',''visible'',''on'',''foreground'',''blue'');'...
                'if vtsst_exind==1;'...
                    'exportar;'...
                'end;'...
                'msgbox(''Fim do teste'',''Obrigado!'',''help'');'...
            'else;'...
                'vtsst_continuar=questdlg(''Deseja treinar de novo?'',''Fim de Treino'',''Sim'',''Não'',''Sim'');'...
                'vtsst_contind=strcmp(vtsst_continuar,''Sim'');'...
                'set(htsst_f,''color'',''white'');'...
                'set(htsst_num,''visible'',''on'',''foreground'',''blue'');'...
                'if vtsst_contind==1;'...
                    'vtsst_tstop=0;'...
                    'eval(ftsst_treinoiniciar_fcn);'...
                'else;'...
                    'set(htsst_num,''string'',''Fim do Treino'',''fontsize'',30);'...
                'end;'...
            'end;'...
            'set([htsstmenuarquivo htsstresultadosexportar htsstmenutreino htsstmenuteste],''enable'',''on'');'...
       'end;'];
   
 htsst_timer=timer('period',vtsst_temptest,...
    'executionmode','fixeddelay',...
    'taskstoexecute',2,...
    'stopfcn',ftsst_timer_fcn,...
    'timerfcn','t=1;');

    
