vucname=0;
vucage=0;
vucsex=2;

hucuserconfig=figure('units','normalized',...
    'menubar','none',...
    'numbertitle','off',...
    'color','white',...
    'name','CONFIGURACAO DO USUARIO',...
    'resize','off',...
    'position',[0.35,0.45,0.25,0.3],...
    'deletefcn','clear huc*');

hucframe1=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.037,0.69,0.93,0.18]);   

hucusername=uicontrol(hucuserconfig,'style','edit',...
    'horizontalalignment','left',...
    'units','normalized',...
    'backgroundcolor','white',...
    'fontsize',9,...
    'fontname','arial',...
    'position',[0.049,0.712,0.9,0.08],...
    'callback','vucname=1;');

hucnametext=uicontrol(hucuserconfig,'style','text',...
    'horizontalalignment','left',...
    'units','normalized',...
    'string','NOME:',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontsize',10,...
    'fontname','arial',...
    'fontweight','bold',...
    'position',[0.045,0.8,0.14,0.06]);

hucframe3=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.537,0.35,0.4,0.3]);   

hucuserage=uicontrol(hucuserconfig,'style','edit',...
    'horizontalalignment','left',...
    'units','normalized',...
    'backgroundcolor','white',...
    'fontsize',9,...
    'fontname','arial',...
    'position',[0.67,0.45,0.15,0.08],...
    'callback','vucage=1;');

hucagetext=uicontrol(hucuserconfig,'style','text',...
    'horizontalalignment','left',...
    'units','normalized',...
    'string','IDADE:',...
    'fontweight','bold',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontsize',10,...
    'fontname','arial',...
    'position',[0.55,0.56,0.14,0.07]);

hucframe2=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.037,0.35,0.4,0.3]);   

hucsextext=uicontrol(hucuserconfig,'style','text',...
    'horizontalalignment','left',...
    'units','normalized',...
    'string','SEXO:',...
    'fontweight','bold',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontsize',10,...
    'fontname','arial',...
    'position',[0.051,0.56,0.14,0.06]);

hucsexcheckm_callback=['vucchf=get(hucsexcheckf,''value'');'...
        'if vucchf==1;'...
            'set(hucsexcheckf,''value'',0);'...
        'end;'...
        'vucsex=1;'];
        
hucsexcheckm=uicontrol(hucuserconfig,'style','checkbox',...
    'horizontalalignment','left',...
    'units','normalized',...
    'string','Masculino',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontsize',9,...
    'fontname','arial',...
    'callback',hucsexcheckm_callback,...
    'position',[0.052,0.46,0.26,0.07]);

hucsexcheckf_callback=['vucchm=get(hucsexcheckm,''value'');'...
        'if vucchm==1;'...
            'set(hucsexcheckm,''value'',0);'...
        'end;'...
        'vucsex=0;'];
        
hucsexcheckf=uicontrol(hucuserconfig,'style','checkbox',...
    'horizontalalignment','left',...
    'units','normalized',...
    'string','Feminino',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontsize',9,...
    'fontname','arial',...
    'callback',hucsexcheckf_callback,...
    'position',[0.052,0.38,0.26,0.07]);

hucokuser_callback=['vucdatachk=1;'...
        'switch vucname;'...
            'case 1;'...
                 'userdata{1}=get(hucusername,''string'');'...
            'case 0;'...
                'vucfillname=questdlg(''Deseja salvar sem especificar nome?'',''Dados incompletos'',''Sim'',''Nao'',''Sim'');'...
                'if vucfillname==''Sim'';'...
                     'vucname=1;'...
                 'else;'...
                    'return;'...                     
                 'end;'...
        'end;'...
        'switch vucage;'...
            'case 1;'...
                 'userdata{2}=get(hucuserage,''string'');'...
            'case 0;'...
                'vucfillage=questdlg(''Deseja salvar sem especificar idade?'',''Dados incompletos'',''Sim'',''Nao'',''Sim'');'...
                'if vucfillage==''Sim'';'...
                     'vucage=1;'...
                 'else;'...
                    'return;'...
                 'end;'...
        'end;'...
        'switch vucsex;'...
            'case 1;'...
                 'userdata{3}=get(hucsexcheckm,''string'');'...
                 'close(hucuserconfig);'...
                 'userok=1;'...
            'case 0;'...
                 'userdata{3}=get(hucsexcheckf,''string'');'...
                 'close(hucuserconfig);'...                 
                 'userok=1;'...
            'otherwise;'...
                'vucfillsex=questdlg(''Deseja salvar sem especificar sexo?'',''Dados incompletos'',''Sim'',''Nao'',''Sim'');'...
                'if vucfillsex==''Sim'';'...
                     'close(hucuserconfig);'...
                     'userok=1;'...
                'end;'...
        'end;'...
        'if tsst_enable==1;'...
            'set(htsst_menuinicioteste,''enable'',''on'');'...
        'end;'...
        'clear huc* vuc*;'];       

hucokuser=uicontrol(hucuserconfig,'style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',10',...
    'position',[0.38,0.1,0.25,0.12],...
    'string','OK',...
    'callback',hucokuser_callback);